import { useEffect, useMemo, useState } from 'react'
import { ActivityIndicator, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native'
import { Ionicons } from '@expo/vector-icons'
import { SafeAreaView } from 'react-native-safe-area-context'
import { listEquipmentOptions, type EquipmentOption } from '../features/core-parity/api/coreParityService'

export function CreateTargetPickerScreen({ title, onBack, onSelect }: { title: string; onBack: () => void; onSelect: (equipmentId: string) => void }) {
  const [items,setItems]=useState<EquipmentOption[]>([])
  const [loading,setLoading]=useState(true)
  const [search,setSearch]=useState('')
  const [error,setError]=useState('')
  useEffect(()=>{ let active=true; void listEquipmentOptions().then((rows)=>{if(active)setItems(rows)}).catch((e)=>{if(active)setError(e instanceof Error?e.message:'Không tải được thiết bị.')}).finally(()=>{if(active)setLoading(false)}); return()=>{active=false} },[])
  const filtered=useMemo(()=>{const q=search.trim().toLowerCase();return q?items.filter((x)=>`${x.equipmentId} ${x.name}`.toLowerCase().includes(q)):items},[items,search])
  return <SafeAreaView style={styles.safe}><View style={styles.header}><Pressable onPress={onBack} style={styles.icon}><Ionicons name="chevron-back" size={26} color="#101828"/></Pressable><View style={styles.headCopy}><Text style={styles.title}>{title}</Text><Text style={styles.sub}>Chọn thiết bị trước khi tạo</Text></View></View><View style={styles.search}><Ionicons name="search" size={18} color="#667085"/><TextInput value={search} onChangeText={setSearch} placeholder="Tìm mã hoặc tên thiết bị" placeholderTextColor="#98A2B3" style={styles.input}/></View>{error?<Text style={styles.error}>{error}</Text>:null}{loading?<View style={styles.center}><ActivityIndicator size="large" color="#155EEF"/></View>:<ScrollView contentContainerStyle={styles.content}>{filtered.map((item)=><Pressable key={item.equipmentId} onPress={()=>onSelect(item.equipmentId)} style={({pressed})=>[styles.row,pressed&&styles.pressed]}><View style={styles.assetIcon}><Ionicons name="cube-outline" size={22} color="#155EEF"/></View><View style={styles.flex}><Text style={styles.name}>{item.name||item.equipmentId}</Text><Text style={styles.meta}>{item.equipmentId}</Text></View><Ionicons name="chevron-forward" size={20} color="#D0D5DD"/></Pressable>)}{!filtered.length?<Text style={styles.empty}>Không có thiết bị phù hợp.</Text>:null}</ScrollView>}</SafeAreaView>
}
const styles=StyleSheet.create({safe:{flex:1,backgroundColor:'#F8FAFC'},header:{minHeight:64,backgroundColor:'#FFF',borderBottomWidth:1,borderBottomColor:'#EAECF0',paddingHorizontal:8,flexDirection:'row',alignItems:'center'},icon:{width:46,height:46,alignItems:'center',justifyContent:'center'},headCopy:{flex:1},title:{fontSize:19,fontWeight:'900',color:'#101828'},sub:{fontSize:12,color:'#667085',marginTop:2},search:{margin:14,height:46,borderWidth:1,borderColor:'#D0D5DD',borderRadius:12,backgroundColor:'#FFF',paddingHorizontal:12,flexDirection:'row',alignItems:'center',gap:8},input:{flex:1,color:'#101828'},content:{padding:14,paddingTop:0,gap:8},row:{minHeight:68,backgroundColor:'#FFF',borderWidth:1,borderColor:'#EAECF0',borderRadius:13,paddingHorizontal:12,flexDirection:'row',alignItems:'center',gap:10},pressed:{opacity:.72},assetIcon:{width:40,height:40,borderRadius:10,backgroundColor:'#EEF4FF',alignItems:'center',justifyContent:'center'},flex:{flex:1},name:{fontSize:15,fontWeight:'800',color:'#101828'},meta:{fontSize:12,color:'#667085',marginTop:3},center:{flex:1,alignItems:'center',justifyContent:'center'},error:{marginHorizontal:14,color:'#B42318'},empty:{textAlign:'center',color:'#667085',padding:28}})
