import { useState } from 'react'
import { ActivityIndicator, Alert, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native'
import { Ionicons } from '@expo/vector-icons'
import { SafeAreaView } from 'react-native-safe-area-context'
import { createMaintenanceRequest } from '../features/requests/requestService'

export function CreateRequestScreen({ equipmentId, sourceId, onBack, onCreated }: { equipmentId: string; sourceId?: string; onBack: () => void; onCreated: (requestId: string) => void }) {
  const [reason, setReason] = useState(''); const [saving, setSaving] = useState(false)
  async function submit() { if (!reason.trim() || saving) return; setSaving(true); try { const result = await createMaintenanceRequest({ equipmentId, reason, sourceId }); Alert.alert('Đã tạo yêu cầu', result.requestId, [{ text: 'Xem yêu cầu', onPress: () => onCreated(result.requestId) }]) } catch (error) { Alert.alert('Không thể tạo yêu cầu', error instanceof Error ? error.message : 'Vui lòng thử lại.') } finally { setSaving(false) } }
 return <SafeAreaView style={styles.safe} edges={['top','bottom']}><View style={styles.header}><Pressable onPress={onBack} style={styles.icon}><Ionicons name="chevron-back" size={26} color="#101828" /></Pressable><Text style={styles.title}>Tạo yêu cầu</Text><View style={styles.icon}/></View><ScrollView contentContainerStyle={styles.content}><View style={styles.asset}><Ionicons name="cube-outline" size={23} color="#155EEF"/><View><Text style={styles.caption}>Thiết bị được quét</Text><Text style={styles.assetId}>{equipmentId}</Text></View></View><Text style={styles.label}>Tiêu đề yêu cầu *</Text><TextInput value={reason} onChangeText={setReason} placeholder="Ví dụ: Máy không khởi động" placeholderTextColor="#98A2B3" style={styles.singleLine}/><Text style={styles.label}>Mô tả chi tiết</Text><TextInput value={reason} onChangeText={setReason} multiline placeholder="Mô tả vấn đề cần hỗ trợ" placeholderTextColor="#98A2B3" style={styles.textarea}/><Text style={styles.label}>Mức ưu tiên</Text><View style={styles.priorityRow}><Text style={styles.priorityActive}>Trung bình</Text><Text style={styles.priority}>Thấp</Text><Text style={styles.priority}>Cao</Text></View></ScrollView><View style={styles.bottom}><Pressable disabled={!reason.trim()||saving} onPress={()=>void submit()} style={[styles.submit,(!reason.trim()||saving)&&styles.disabled]}>{saving?<ActivityIndicator color="#FFF"/>:<Text style={styles.submitText}>Tạo yêu cầu</Text>}</Pressable></View></SafeAreaView>
}
const styles=StyleSheet.create({safe:{flex:1,backgroundColor:'#F1F1FA'},header:{minHeight:60,paddingHorizontal:8,flexDirection:'row',alignItems:'center',justifyContent:'space-between',backgroundColor:'#FFF',borderBottomWidth:StyleSheet.hairlineWidth,borderBottomColor:'#E5E5EF'},icon:{width:46,height:46,alignItems:'center',justifyContent:'center'},title:{fontSize:20,fontWeight:'900',color:'#101828'},content:{padding:14,paddingBottom:30},asset:{padding:15,flexDirection:'row',alignItems:'center',gap:10,borderRadius:17,backgroundColor:'#E9EDFF'},caption:{fontSize:12,color:'#667085'},assetId:{marginTop:3,fontSize:16,fontWeight:'900',color:'#155EEF'},label:{marginTop:22,marginBottom:8,fontSize:13.5,fontWeight:'900',color:'#344054'},singleLine:{minHeight:54,paddingHorizontal:14,borderRadius:15,borderWidth:1,borderColor:'#D7D8E5',backgroundColor:'#FFF',fontSize:15,color:'#101828'},textarea:{minHeight:145,padding:14,borderRadius:16,borderWidth:1,borderColor:'#D7D8E5',backgroundColor:'#FFF',fontSize:15,color:'#101828',textAlignVertical:'top'},priorityRow:{flexDirection:'row',gap:8},priority:{paddingHorizontal:14,paddingVertical:10,borderRadius:18,borderWidth:1,borderColor:'#D9DAE7',backgroundColor:'#FFF',fontSize:12,fontWeight:'800',color:'#475467'},priorityActive:{paddingHorizontal:14,paddingVertical:10,borderRadius:18,backgroundColor:'#536DFE',fontSize:12,fontWeight:'800',color:'#FFF'},bottom:{padding:16,backgroundColor:'#FFF',borderTopWidth:StyleSheet.hairlineWidth,borderTopColor:'#EAECF0'},submit:{minHeight:52,borderRadius:26,alignItems:'center',justifyContent:'center',backgroundColor:'#536DFE'},disabled:{opacity:.45},submitText:{fontSize:16,fontWeight:'900',color:'#FFF'}})
