import { useState } from 'react'
import { ActivityIndicator, Alert, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native'
import { Ionicons } from '@expo/vector-icons'
import { SafeAreaView } from 'react-native-safe-area-context'
import { createMaintenanceRequest } from '../features/requests/requestService'

export function CreateRequestScreen({ equipmentId, sourceId, onBack, onCreated }: { equipmentId: string; sourceId?: string; onBack: () => void; onCreated: (requestId: string) => void }) {
  const [title,setTitle]=useState('')
  const [description,setDescription]=useState('')
  const [priority,setPriority]=useState('MEDIUM')
  const [saving, setSaving] = useState(false)
  async function submit() { if (!title.trim() || saving) return; setSaving(true); try { const result = await createMaintenanceRequest({ equipmentId, title, description, priority, sourceId }); Alert.alert('Đã tạo yêu cầu', result.requestId, [{ text: 'Xem yêu cầu', onPress: () => onCreated(result.requestId) }]) } catch (error) { Alert.alert('Không thể tạo yêu cầu', error instanceof Error ? error.message : 'Vui lòng thử lại.') } finally { setSaving(false) } }
  const priorities:Array<[string,string]>=[['LOW','Thấp'],['MEDIUM','Trung bình'],['HIGH','Cao'],['CRITICAL','Khẩn cấp']]
 return <SafeAreaView style={styles.safe} edges={['top','bottom']}><View style={styles.header}><Pressable onPress={onBack} style={styles.icon}><Ionicons name="chevron-back" size={26} color="#101828" /></Pressable><Text style={styles.title}>Tạo yêu cầu</Text><View style={styles.icon}/></View><ScrollView contentContainerStyle={styles.content}><View style={styles.asset}><Ionicons name="cube-outline" size={23} color="#155EEF"/><View><Text style={styles.caption}>Thiết bị được quét</Text><Text style={styles.assetId}>{equipmentId}</Text></View></View><Text style={styles.label}>Tiêu đề yêu cầu *</Text><TextInput value={title} onChangeText={setTitle} placeholder="Ví dụ: Máy không khởi động" placeholderTextColor="#98A2B3" style={styles.singleLine}/><Text style={styles.label}>Mô tả chi tiết</Text><TextInput value={description} onChangeText={setDescription} multiline placeholder="Mô tả vấn đề cần hỗ trợ" placeholderTextColor="#98A2B3" style={styles.textarea}/><Text style={styles.label}>Mức ưu tiên</Text><View style={styles.priorityRow}>{priorities.map(([value,label])=><Pressable key={value} onPress={()=>setPriority(value)} style={[styles.priority,priority===value&&styles.priorityActive]}><Text style={[styles.priorityText,priority===value&&styles.priorityTextActive]}>{label}</Text></Pressable>)}</View></ScrollView><View style={styles.bottom}><Pressable disabled={!title.trim()||saving} onPress={()=>void submit()} style={[styles.submit,(!title.trim()||saving)&&styles.disabled]}>{saving?<ActivityIndicator color="#FFF"/>:<Text style={styles.submitText}>Tạo yêu cầu</Text>}</Pressable></View></SafeAreaView>
}
const styles=StyleSheet.create({safe:{flex:1,backgroundColor:'#F1F1FA'},header:{minHeight:60,paddingHorizontal:8,flexDirection:'row',alignItems:'center',justifyContent:'space-between',backgroundColor:'#FFF',borderBottomWidth:StyleSheet.hairlineWidth,borderBottomColor:'#E5E5EF'},icon:{width:46,height:46,alignItems:'center',justifyContent:'center'},title:{fontSize:20,fontWeight:'900',color:'#101828'},content:{padding:14,paddingBottom:30},asset:{padding:15,flexDirection:'row',alignItems:'center',gap:10,borderRadius:17,backgroundColor:'#E9EDFF'},caption:{fontSize:12,color:'#667085'},assetId:{marginTop:3,fontSize:16,fontWeight:'900',color:'#155EEF'},label:{marginTop:22,marginBottom:8,fontSize:13.5,fontWeight:'900',color:'#344054'},singleLine:{minHeight:54,paddingHorizontal:14,borderRadius:15,borderWidth:1,borderColor:'#D7D8E5',backgroundColor:'#FFF',fontSize:15,color:'#101828'},textarea:{minHeight:145,padding:14,borderRadius:16,borderWidth:1,borderColor:'#D7D8E5',backgroundColor:'#FFF',fontSize:15,color:'#101828',textAlignVertical:'top'},priorityRow:{flexDirection:'row',flexWrap:'wrap',gap:8},priority:{paddingHorizontal:14,paddingVertical:10,borderRadius:18,borderWidth:1,borderColor:'#D9DAE7',backgroundColor:'#FFF'},priorityActive:{borderColor:'#536DFE',backgroundColor:'#536DFE'},priorityText:{fontSize:12,fontWeight:'800',color:'#475467'},priorityTextActive:{color:'#FFF'},bottom:{padding:16,backgroundColor:'#FFF',borderTopWidth:StyleSheet.hairlineWidth,borderTopColor:'#EAECF0'},submit:{minHeight:52,borderRadius:26,alignItems:'center',justifyContent:'center',backgroundColor:'#536DFE'},disabled:{opacity:.45},submitText:{fontSize:16,fontWeight:'900',color:'#FFF'}})
