import { useState } from 'react'
import { ActivityIndicator, Alert, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native'
import { Ionicons } from '@expo/vector-icons'
import { SafeAreaView } from 'react-native-safe-area-context'
import { createMaintenanceRequest } from '../features/requests/requestService'

export function CreateRequestScreen({ equipmentId, sourceId, onBack, onCreated }: { equipmentId: string; sourceId?: string; onBack: () => void; onCreated: (requestId: string) => void }) {
  const [reason, setReason] = useState(''); const [saving, setSaving] = useState(false)
  async function submit() { if (!reason.trim() || saving) return; setSaving(true); try { const result = await createMaintenanceRequest({ equipmentId, reason, sourceId }); Alert.alert('Đã tạo yêu cầu', result.requestId, [{ text: 'Xem yêu cầu', onPress: () => onCreated(result.requestId) }]) } catch (error) { Alert.alert('Không thể tạo yêu cầu', error instanceof Error ? error.message : 'Vui lòng thử lại.') } finally { setSaving(false) } }
  return <SafeAreaView style={styles.safe} edges={['top','bottom']}><View style={styles.header}><Pressable onPress={onBack} style={styles.icon}><Ionicons name="chevron-back" size={26} color="#101828" /></Pressable><Text style={styles.title}>Tạo yêu cầu</Text><View style={styles.icon}/></View><ScrollView contentContainerStyle={styles.content}><View style={styles.asset}><Ionicons name="cube-outline" size={23} color="#155EEF"/><View><Text style={styles.caption}>Thiết bị được quét</Text><Text style={styles.assetId}>{equipmentId}</Text></View></View><Text style={styles.label}>Nội dung yêu cầu *</Text><TextInput value={reason} onChangeText={setReason} multiline placeholder="Mô tả vấn đề cần hỗ trợ" placeholderTextColor="#98A2B3" style={styles.textarea}/></ScrollView><View style={styles.bottom}><Pressable disabled={!reason.trim()||saving} onPress={()=>void submit()} style={[styles.submit,(!reason.trim()||saving)&&styles.disabled]}>{saving?<ActivityIndicator color="#FFF"/>:<Text style={styles.submitText}>Tạo yêu cầu</Text>}</Pressable></View></SafeAreaView>
}
const styles=StyleSheet.create({safe:{flex:1,backgroundColor:'#F8F9FB'},header:{minHeight:60,paddingHorizontal:8,flexDirection:'row',alignItems:'center',justifyContent:'space-between',backgroundColor:'#FFF',borderBottomWidth:StyleSheet.hairlineWidth,borderBottomColor:'#EAECF0'},icon:{width:46,height:46,alignItems:'center',justifyContent:'center'},title:{fontSize:20,fontWeight:'900',color:'#101828'},content:{padding:16},asset:{padding:14,flexDirection:'row',alignItems:'center',gap:10,borderRadius:14,backgroundColor:'#EFF4FF'},caption:{fontSize:12,color:'#667085'},assetId:{marginTop:3,fontSize:16,fontWeight:'900',color:'#155EEF'},label:{marginTop:22,marginBottom:8,fontSize:14,fontWeight:'900',color:'#344054'},textarea:{minHeight:145,padding:13,borderRadius:12,borderWidth:1,borderColor:'#D0D5DD',backgroundColor:'#FFF',fontSize:15,color:'#101828',textAlignVertical:'top'},bottom:{padding:16,backgroundColor:'#FFF',borderTopWidth:StyleSheet.hairlineWidth,borderTopColor:'#EAECF0'},submit:{minHeight:52,borderRadius:26,alignItems:'center',justifyContent:'center',backgroundColor:'#155EEF'},disabled:{opacity:.45},submitText:{fontSize:16,fontWeight:'900',color:'#FFF'}})
