import { Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native'
import { Ionicons } from '@expo/vector-icons'
import { SafeAreaView } from 'react-native-safe-area-context'

export function MasterDataFormScreen({ title, fields, onBack }: { title: string; fields: Array<{ label: string; placeholder: string; multiline?: boolean }>; onBack: () => void }) {
  return <SafeAreaView style={styles.safe} edges={['top','bottom']}><View style={styles.header}><Pressable onPress={onBack} style={styles.icon}><Ionicons name="chevron-back" size={26} color="#101828" /></Pressable><Text style={styles.title}>{title}</Text><View style={styles.icon}/></View><ScrollView contentContainerStyle={styles.content} keyboardShouldPersistTaps="handled">{fields.map((field)=><View key={field.label} style={styles.field}><Text style={styles.label}>{field.label}</Text><TextInput placeholder={field.placeholder} placeholderTextColor="#98A2B3" multiline={field.multiline} style={[styles.input,field.multiline&&styles.textarea]}/></View>)}<View style={styles.note}><Ionicons name="information-circle-outline" size={19} color="#536DFE"/><Text style={styles.noteText}>Màn hình mẫu theo UpKeep. Thông tin sẽ được lưu khi nối dữ liệu thật.</Text></View></ScrollView><View style={styles.bottom}><Pressable style={styles.save}><Text style={styles.saveText}>Lưu</Text></Pressable></View></SafeAreaView>
}

const styles=StyleSheet.create({safe:{flex:1,backgroundColor:'#F1F1FA'},header:{minHeight:60,paddingHorizontal:8,flexDirection:'row',alignItems:'center',justifyContent:'space-between',backgroundColor:'#FFF',borderBottomWidth:StyleSheet.hairlineWidth,borderBottomColor:'#E5E5EF'},icon:{width:46,height:46,alignItems:'center',justifyContent:'center'},title:{fontSize:20,fontWeight:'900',color:'#101828'},content:{padding:14,paddingBottom:30},field:{marginBottom:18},label:{marginBottom:8,fontSize:13.5,fontWeight:'900',color:'#344054'},input:{minHeight:54,paddingHorizontal:14,borderRadius:15,borderWidth:1,borderColor:'#D7D8E5',backgroundColor:'#FFF',fontSize:15,color:'#101828'},textarea:{minHeight:120,paddingTop:14,textAlignVertical:'top'},note:{padding:13,flexDirection:'row',gap:8,borderRadius:13,backgroundColor:'#E9EDFF'},noteText:{flex:1,fontSize:12.5,lineHeight:18,color:'#344054'},bottom:{padding:16,borderTopWidth:StyleSheet.hairlineWidth,borderTopColor:'#EAECF0',backgroundColor:'#FFF'},save:{minHeight:52,borderRadius:26,alignItems:'center',justifyContent:'center',backgroundColor:'#536DFE'},saveText:{fontSize:16,fontWeight:'900',color:'#FFF'}})
