import { useEffect, useMemo, useState } from 'react'
import { ActivityIndicator, Alert, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native'
import { Ionicons } from '@expo/vector-icons'
import { SafeAreaView } from 'react-native-safe-area-context'
import { listEquipmentOptions, type EquipmentOption } from '../features/core-parity/api/coreParityService'
import { saveMeter } from '../features/preventive-maintenance'

export function MeterFormScreen({ onBack, onSaved }: { onBack: () => void; onSaved: () => void }) {
  const [equipment,setEquipment]=useState<EquipmentOption[]>([])
  const [equipmentId,setEquipmentId]=useState('')
  const [search,setSearch]=useState('')
  const [name,setName]=useState('')
  const [unit,setUnit]=useState('')
  const [meterType,setMeterType]=useState('COUNTER')
  const [rollover,setRollover]=useState('')
  const [saving,setSaving]=useState(false)
  useEffect(()=>{void listEquipmentOptions().then(setEquipment).catch(()=>setEquipment([]))},[])
  const filtered=useMemo(()=>{const q=search.trim().toLowerCase();return q?equipment.filter((x)=>`${x.id} ${x.name}`.toLowerCase().includes(q)):equipment},[equipment,search])
  async function submit(){if(!equipmentId||!name.trim()||!unit.trim())return Alert.alert('Thiếu thông tin','Chọn thiết bị, nhập tên meter và đơn vị.');setSaving(true);try{await saveMeter({equipmentId,name:name.trim(),unit:unit.trim(),meterType,rolloverValue:rollover.trim()?Number(rollover):null});Alert.alert('Đã tạo meter',name,[{text:'OK',onPress:onSaved}])}catch(e){Alert.alert('Không tạo được meter',e instanceof Error?e.message:'Có lỗi xảy ra.')}finally{setSaving(false)}}
  return <SafeAreaView style={styles.safe}><View style={styles.header}><Pressable onPress={onBack} style={styles.icon}><Ionicons name="chevron-back" size={26} color="#101828"/></Pressable><Text style={styles.title}>Tạo đồng hồ đo</Text><View style={styles.icon}/></View><ScrollView contentContainerStyle={styles.content} keyboardShouldPersistTaps="handled"><Text style={styles.label}>Thiết bị *</Text><TextInput value={search} onChangeText={setSearch} placeholder="Tìm thiết bị" placeholderTextColor="#98A2B3" style={styles.input}/><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.pills}>{filtered.slice(0,30).map((item)=><Pressable key={item.id} onPress={()=>setEquipmentId(item.id)} style={[styles.pill,item.id===equipmentId&&styles.pillActive]}><Text style={[styles.pillText,item.id===equipmentId&&styles.pillTextActive]}>{item.name}</Text></Pressable>)}</ScrollView><Text style={styles.label}>Tên meter *</Text><TextInput value={name} onChangeText={setName} placeholder="Ví dụ: Giờ chạy máy" placeholderTextColor="#98A2B3" style={styles.input}/><Text style={styles.label}>Loại</Text><View style={styles.pills}>{['COUNTER','GAUGE'].map((type)=><Pressable key={type} onPress={()=>setMeterType(type)} style={[styles.pill,type===meterType&&styles.pillActive]}><Text style={[styles.pillText,type===meterType&&styles.pillTextActive]}>{type}</Text></Pressable>)}</View><Text style={styles.label}>Đơn vị *</Text><TextInput value={unit} onChangeText={setUnit} placeholder="h, cycles, km..." placeholderTextColor="#98A2B3" style={styles.input}/><Text style={styles.label}>Rollover</Text><TextInput value={rollover} onChangeText={setRollover} keyboardType="decimal-pad" placeholder="Không bắt buộc" placeholderTextColor="#98A2B3" style={styles.input}/><Pressable disabled={saving} onPress={()=>void submit()} style={[styles.submit,saving&&styles.disabled]}>{saving?<ActivityIndicator color="#FFF"/>:<Text style={styles.submitText}>Tạo meter</Text>}</Pressable></ScrollView></SafeAreaView>
}
const styles=StyleSheet.create({safe:{flex:1,backgroundColor:'#F8FAFC'},header:{height:60,backgroundColor:'#FFF',borderBottomWidth:1,borderBottomColor:'#EAECF0',flexDirection:'row',alignItems:'center',justifyContent:'space-between',paddingHorizontal:8},icon:{width:46,height:46,alignItems:'center',justifyContent:'center'},title:{fontSize:19,fontWeight:'900',color:'#101828'},content:{padding:16,paddingBottom:32},label:{marginTop:16,marginBottom:7,fontSize:13,fontWeight:'800',color:'#344054'},input:{minHeight:46,borderWidth:1,borderColor:'#D0D5DD',borderRadius:11,paddingHorizontal:12,backgroundColor:'#FFF',color:'#101828'},pills:{flexDirection:'row',gap:8,paddingVertical:8},pill:{paddingHorizontal:12,paddingVertical:9,borderRadius:18,borderWidth:1,borderColor:'#D0D5DD',backgroundColor:'#FFF'},pillActive:{backgroundColor:'#155EEF',borderColor:'#155EEF'},pillText:{fontSize:12,fontWeight:'700',color:'#475467'},pillTextActive:{color:'#FFF'},submit:{marginTop:28,minHeight:50,borderRadius:25,backgroundColor:'#155EEF',alignItems:'center',justifyContent:'center'},submitText:{color:'#FFF',fontSize:16,fontWeight:'900'},disabled:{opacity:.55}})
