import { useEffect, useState } from 'react'
import { ActivityIndicator, Alert, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native'
import { Ionicons } from '@expo/vector-icons'
import { SafeAreaView } from 'react-native-safe-area-context'
import {
  createTag, createTagSet, loadMobileLastParity, saveAssetFinancialProfile, saveChecklistRule,
  setEntityTag, setSignatureRequirement, setTagSetMember, signWorkOrder,
  type AssetFinancialProfile, type MobileLastParitySnapshot,
} from '../features/mobile-last-parity/api/mobileLastParityService'

type Tab='signature'|'checklist'|'asset'|'tags'
const TABS:Array<{id:Tab;label:string}>=[{id:'signature',label:'Signature'},{id:'checklist',label:'Checklist Rules'},{id:'asset',label:'Asset Life'},{id:'tags',label:'Tags / Sets'}]
function Btn({label,onPress,disabled=false}:{label:string;onPress:()=>void;disabled?:boolean}){return <Pressable disabled={disabled} onPress={onPress} style={[s.btn,disabled&&s.disabled]}><Text style={s.btnText}>{label}</Text></Pressable>}
function Pills({items,value,onChange}:{items:Array<{id:string;label:string}>;value:string;onChange:(v:string)=>void}){return <ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={s.pills}>{items.map(x=><Pressable key={x.id} onPress={()=>onChange(x.id)} style={[s.pill,x.id===value&&s.pillOn]}><Text style={[s.pillText,x.id===value&&s.pillTextOn]}>{x.label}</Text></Pressable>)}</ScrollView>}
function Field({value,onChange,placeholder}:{value:string;onChange:(v:string)=>void;placeholder:string}){return <TextInput style={s.input} value={value} onChangeText={onChange} placeholder={placeholder}/>} 

export function MobileLastParityScreen({onBack}:{onBack:()=>void}){
  const [tab,setTab]=useState<Tab>('signature'); const [data,setData]=useState<MobileLastParitySnapshot|null>(null); const [loading,setLoading]=useState(true)
  async function load(){setLoading(true);try{setData(await loadMobileLastParity())}catch(e){Alert.alert('UpKeep parity',e instanceof Error?e.message:'Không tải được dữ liệu.')}finally{setLoading(false)}}
  useEffect(()=>{void load()},[])
  return <SafeAreaView style={s.safe} edges={['top','bottom']}><View style={s.header}><Pressable onPress={onBack} style={s.icon}><Ionicons name="chevron-back" size={26}/></Pressable><View style={{flex:1}}><Text style={s.title}>UpKeep parity cuối</Text><Text style={s.sub}>Signature · Rules · Asset life · Tags/Sets</Text></View><Pressable onPress={()=>void load()} style={s.icon}><Ionicons name="refresh" size={21}/></Pressable></View><Pills items={TABS} value={tab} onChange={v=>setTab(v as Tab)}/>{loading?<View style={s.center}><ActivityIndicator size="large" color="#155EEF"/></View>:tab==='signature'?<SignaturePanel data={data} reload={load}/>:tab==='checklist'?<RulesPanel data={data} reload={load}/>:tab==='asset'?<AssetPanel data={data} reload={load}/>:<TagsSetsPanel data={data} reload={load}/>}</SafeAreaView>
}

function SignaturePanel({data,reload}:{data:MobileLastParitySnapshot|null;reload:()=>Promise<void>}){
  const rows=data?.workOrders||[]; const [id,setId]=useState(''); const [name,setName]=useState(''); const [role,setRole]=useState('TECHNICIAN'); const [sig,setSig]=useState('')
  useEffect(()=>{if(!id&&rows[0])setId(rows[0].id)},[id,rows]); const wo=rows.find(x=>x.id===id)
  async function sign(){if(!id||!name.trim()||!sig.trim())return Alert.alert('Thiếu chữ ký');try{await signWorkOrder({workOrderId:id,signerName:name.trim(),signerRole:role,signatureText:sig.trim()});setSig('');await reload()}catch(e){Alert.alert('Signature',e instanceof Error?e.message:'Không lưu được.')}}
  return <ScrollView contentContainerStyle={s.body}><Text style={s.h2}>Work Order Signature</Text><Text style={s.muted}>Nếu bật bắt buộc, backend sẽ chặn COMPLETE cho đến khi có chữ ký.</Text><Pills items={rows.slice(0,60).map(x=>({id:x.id,label:x.id}))} value={id} onChange={setId}/>{wo?<View style={s.card}><Text style={s.cardTitle}>{wo.id}</Text><Text style={s.muted}>{wo.status} · {wo.reason||'Không mô tả'}</Text><Pressable onPress={()=>void setSignatureRequirement(wo.id,!wo.signatureRequired).then(reload)}><Text style={s.toggle}>{wo.signatureRequired?'✓ Bắt buộc chữ ký':'○ Không bắt buộc'}</Text></Pressable><Field value={name} onChange={setName} placeholder="Tên người ký *"/><Field value={role} onChange={setRole} placeholder="Vai trò"/><TextInput style={[s.input,{minHeight:88,textAlignVertical:'top',fontSize:18,fontStyle:'italic'}]} value={sig} onChangeText={setSig} multiline placeholder="Ký/xác nhận tại đây *"/><Btn label="Lưu chữ ký" onPress={()=>void sign()}/>{wo.signatures.map(x=><View key={x.id} style={s.inner}><Text style={s.cardTitle}>{x.name}</Text><Text style={s.muted}>{x.role||'—'} · {new Date(x.signedAt).toLocaleString('vi-VN')}</Text><Text style={s.signature}>{x.text}</Text></View>)}</View>:<Text style={s.muted}>Chưa có Work Order.</Text>}</ScrollView>
}

function RulesPanel({data,reload}:{data:MobileLastParitySnapshot|null;reload:()=>Promise<void>}){
  const rows=data?.checklistRules||[]; const [id,setId]=useState(''); const row=rows.find(x=>x.templateItemId===id); const [locked,setLocked]=useState(false); const [role,setRole]=useState(''); const [source,setSource]=useState(''); const [op,setOp]=useState('EQUALS'); const [value,setValue]=useState('')
  useEffect(()=>{if(!id&&rows[0])setId(rows[0].templateItemId)},[id,rows]); useEffect(()=>{if(row){setLocked(row.locked);setRole(row.restrictedRole||'');setSource(row.conditionItemId||'');setOp(row.conditionOperator||'EQUALS');setValue(row.conditionValue||'')}},[row])
  async function save(){if(!row)return;try{await saveChecklistRule({templateItemId:row.templateItemId,locked,restrictedRole:role,conditionItemId:source,conditionOperator:source?op:'',conditionValue:source?value:''});await reload()}catch(e){Alert.alert('Checklist Rules',e instanceof Error?e.message:'Không lưu được.')}}
  return <ScrollView contentContainerStyle={s.body}><Text style={s.h2}>Conditional / Locked Tasks</Text><Text style={s.muted}>Rule được propagate xuống checklist WO và backend kiểm tra khi technician hoàn tất task.</Text><Pills items={rows.slice(0,100).map(x=>({id:x.templateItemId,label:x.label}))} value={id} onChange={setId}/>{row?<View style={s.card}><Text style={s.cardTitle}>{row.label}</Text><Pressable onPress={()=>setLocked(v=>!v)}><Text style={s.toggle}>{locked?'✓ Locked / Restricted':'○ Không khóa'}</Text></Pressable><Field value={role} onChange={setRole} placeholder="Role được phép, ví dụ QUALITY"/><Text style={s.label}>Điều kiện hiển thị/thực hiện</Text><Pills items={[{id:'',label:'Không điều kiện'},...rows.filter(x=>x.templateId===row.templateId&&x.templateItemId!==row.templateItemId).map(x=>({id:x.templateItemId,label:x.label}))]} value={source} onChange={setSource}/>{source?<><Pills items={['EQUALS','NOT_EQUALS','GT','GTE','LT','LTE','CONTAINS'].map(x=>({id:x,label:x}))} value={op} onChange={setOp}/><Field value={value} onChange={setValue} placeholder="Giá trị điều kiện"/></>:null}<Btn label="Lưu rule" onPress={()=>void save()}/></View>:null}</ScrollView>
}

function AssetPanel({data,reload}:{data:MobileLastParitySnapshot|null;reload:()=>Promise<void>}){
  const rows=data?.equipment||[]; const [id,setId]=useState(''); const row=rows.find(x=>x.id===id); const [f,setF]=useState<Record<string,string>>({})
  useEffect(()=>{if(!id&&rows[0])setId(rows[0].id)},[id,rows]); useEffect(()=>{const p=row?.profile;setF({purchaseDate:p?.purchaseDate||'',purchaseCost:p?.purchaseCost?.toString()||'',warrantyExpiry:p?.warrantyExpiry||'',usefulLifeMonths:p?.usefulLifeMonths?.toString()||'',salvageValue:p?.salvageValue?.toString()||'',depreciationMethod:p?.depreciationMethod||'STRAIGHT_LINE',replacementTargetDate:p?.replacementTargetDate||''})},[row]); const set=(k:string,v:string)=>setF(x=>({...x,[k]:v}))
  async function save(){if(!id)return;const p:AssetFinancialProfile={purchaseDate:f.purchaseDate||null,purchaseCost:f.purchaseCost?Number(f.purchaseCost):null,warrantyExpiry:f.warrantyExpiry||null,usefulLifeMonths:f.usefulLifeMonths?Number(f.usefulLifeMonths):null,salvageValue:f.salvageValue?Number(f.salvageValue):null,depreciationMethod:f.depreciationMethod||'STRAIGHT_LINE',replacementTargetDate:f.replacementTargetDate||null};try{await saveAssetFinancialProfile(id,p);await reload()}catch(e){Alert.alert('Asset Life',e instanceof Error?e.message:'Không lưu được.')}}
  return <ScrollView contentContainerStyle={s.body}><Text style={s.h2}>Warranty · Useful Life · Depreciation</Text><Pills items={rows.slice(0,100).map(x=>({id:x.id,label:x.name||x.id}))} value={id} onChange={setId}/>{row?<View style={s.card}>{[['purchaseDate','Ngày mua YYYY-MM-DD'],['purchaseCost','Giá mua'],['warrantyExpiry','Hết bảo hành YYYY-MM-DD'],['usefulLifeMonths','Tuổi thọ (tháng)'],['salvageValue','Giá trị thu hồi'],['replacementTargetDate','Ngày dự kiến thay YYYY-MM-DD']].map(([k,p])=><Field key={k} value={f[k]||''} onChange={v=>set(k,v)} placeholder={p}/>)}<Pills items={['STRAIGHT_LINE','DECLINING_BALANCE','NONE'].map(x=>({id:x,label:x}))} value={f.depreciationMethod||'STRAIGHT_LINE'} onChange={v=>set('depreciationMethod',v)}/><Btn label="Lưu vòng đời tài sản" onPress={()=>void save()}/></View>:null}</ScrollView>
}

function TagsSetsPanel({data,reload}:{data:MobileLastParitySnapshot|null;reload:()=>Promise<void>}){
  const [tagName,setTagName]=useState(''); const [color,setColor]=useState('#155EEF'); const [setName,setSetName]=useState(''); const [setDesc,setSetDesc]=useState(''); const [selectedSet,setSelectedSet]=useState(''); const [entityType,setEntityType]=useState<'ASSET'|'WORK_ORDER'>('ASSET'); const [entityId,setEntityId]=useState('')
  const tags=data?.tags||[]; const sets=data?.tagSets||[]; const targets=entityType==='ASSET'?(data?.equipment||[]).map(x=>({id:x.id,label:x.name||x.id})):(data?.workOrders||[]).map(x=>({id:x.id,label:x.id})); const assigned=new Set((data?.entityTags||[]).filter(x=>x.entityType===entityType&&x.entityId===entityId).map(x=>x.tagId)); const activeSet=sets.find(x=>x.id===selectedSet)
  useEffect(()=>{if(targets[0]&&!targets.some(x=>x.id===entityId))setEntityId(targets[0].id)},[entityId,targets]); useEffect(()=>{if(!selectedSet&&sets[0])setSelectedSet(sets[0].id)},[selectedSet,sets])
  async function addTag(){if(!tagName.trim())return;try{await createTag(tagName.trim(),color);setTagName('');await reload()}catch(e){Alert.alert('Tag',e instanceof Error?e.message:'Không tạo được.')}} async function addSet(){if(!setName.trim())return;try{const id=await createTagSet(setName.trim(),setDesc.trim());setSelectedSet(id);setSetName('');setSetDesc('');await reload()}catch(e){Alert.alert('Set',e instanceof Error?e.message:'Không tạo được.')}}
  return <ScrollView contentContainerStyle={s.body}><Text style={s.h2}>Tags / Sets</Text><View style={s.card}><Text style={s.cardTitle}>Tạo Tag</Text><Field value={tagName} onChange={setTagName} placeholder="Tên tag *"/><Field value={color} onChange={setColor} placeholder="#155EEF"/><Btn label="Tạo Tag" onPress={()=>void addTag()}/></View><View style={s.card}><Text style={s.cardTitle}>Tạo Set</Text><Field value={setName} onChange={setSetName} placeholder="Tên bộ thẻ *"/><Field value={setDesc} onChange={setSetDesc} placeholder="Mô tả"/><Btn label="Tạo Set" onPress={()=>void addSet()}/></View>{sets.length?<><Text style={s.label}>Bộ thẻ</Text><Pills items={sets.map(x=>({id:x.id,label:x.name}))} value={selectedSet} onChange={setSelectedSet}/>{activeSet?tags.map(tag=>{const on=activeSet.tagIds.includes(tag.id);return <Pressable key={`set-${tag.id}`} onPress={()=>void setTagSetMember({setId:activeSet.id,tagId:tag.id,enabled:!on}).then(reload)} style={[s.row,on&&s.rowOn]}><View style={[s.dot,{backgroundColor:tag.color||'#98A2B3'}]}/><Text style={s.rowText}>{tag.name}</Text><Ionicons name={on?'checkmark-circle':'ellipse-outline'} size={22} color={on?'#027A48':'#98A2B3'}/></Pressable>}) : null}</>:null}<Text style={s.label}>Gắn Tag vào dữ liệu</Text><Pills items={[{id:'ASSET',label:'Asset'},{id:'WORK_ORDER',label:'Work Order'}]} value={entityType} onChange={v=>setEntityType(v as 'ASSET'|'WORK_ORDER')}/><Pills items={targets.slice(0,100)} value={entityId} onChange={setEntityId}/>{tags.map(tag=>{const on=assigned.has(tag.id);return <Pressable key={tag.id} onPress={()=>void setEntityTag({entityType,entityId,tagId:tag.id,enabled:!on}).then(reload)} style={[s.row,on&&s.rowOn]}><View style={[s.dot,{backgroundColor:tag.color||'#98A2B3'}]}/><View style={{flex:1}}><Text style={s.rowText}>{tag.name}</Text><Text style={s.muted}>{tag.usageCount} liên kết</Text></View><Ionicons name={on?'checkmark-circle':'ellipse-outline'} size={22} color={on?'#027A48':'#98A2B3'}/></Pressable>})}</ScrollView>
}

const s=StyleSheet.create({safe:{flex:1,backgroundColor:'#FFF'},header:{minHeight:64,flexDirection:'row',alignItems:'center',paddingHorizontal:10,borderBottomWidth:StyleSheet.hairlineWidth,borderBottomColor:'#EAECF0'},icon:{width:42,height:42,alignItems:'center',justifyContent:'center'},title:{fontSize:20,fontWeight:'900',color:'#101828'},sub:{fontSize:12,color:'#667085'},pills:{gap:8,paddingHorizontal:14,paddingVertical:10},pill:{paddingHorizontal:12,paddingVertical:8,borderRadius:999,backgroundColor:'#F2F4F7'},pillOn:{backgroundColor:'#155EEF'},pillText:{fontSize:13,fontWeight:'700',color:'#344054'},pillTextOn:{color:'#FFF'},center:{flex:1,alignItems:'center',justifyContent:'center'},body:{padding:14,paddingBottom:40,gap:12},h2:{fontSize:21,fontWeight:'900',color:'#101828'},muted:{fontSize:13,color:'#667085'},card:{borderWidth:1,borderColor:'#EAECF0',borderRadius:14,padding:14,gap:10},inner:{backgroundColor:'#F9FAFB',borderRadius:10,padding:10,gap:3},cardTitle:{fontSize:15,fontWeight:'800',color:'#101828'},input:{borderWidth:1,borderColor:'#D0D5DD',borderRadius:10,paddingHorizontal:12,paddingVertical:10,fontSize:14,color:'#101828'},btn:{backgroundColor:'#155EEF',padding:12,borderRadius:10,alignItems:'center'},btnText:{fontWeight:'800',color:'#FFF'},disabled:{opacity:.45},toggle:{fontSize:14,fontWeight:'800',color:'#155EEF',paddingVertical:6},label:{fontSize:14,fontWeight:'800',color:'#344054'},signature:{fontSize:20,fontStyle:'italic',marginTop:5},row:{flexDirection:'row',alignItems:'center',gap:10,borderWidth:1,borderColor:'#EAECF0',borderRadius:12,padding:12},rowOn:{borderColor:'#12B76A',backgroundColor:'#ECFDF3'},rowText:{flex:1,fontWeight:'800',color:'#101828'},dot:{width:14,height:14,borderRadius:7}})
