import { useEffect, useMemo, useState } from 'react'
import { ActivityIndicator, Alert, Pressable, ScrollView, StyleSheet, Switch, Text, TextInput, View } from 'react-native'
import { Ionicons } from '@expo/vector-icons'
import { SafeAreaView } from 'react-native-safe-area-context'
import { listChecklistTemplates, listEquipmentOptions, type ChecklistTemplate, type EquipmentOption } from '../features/core-parity/api/coreParityService'
import { createWorkOrderFromTemplate, loadOperationsParity, saveRequestPortalSettings, saveWorkOrderCategory, saveWorkOrderTemplate, setAssetCustody, type OperationsSnapshot } from '../features/operations-parity/api/operationsParityService'

type Tab='templates'|'portal'|'custody'|'categories'
const TABS:Array<{id:Tab;label:string}>=[{id:'templates',label:'WO Templates'},{id:'portal',label:'Request Portal'},{id:'custody',label:'Check-in/out'},{id:'categories',label:'Categories'}]
function Pill({active,label,onPress}:{active:boolean;label:string;onPress:()=>void}){return <Pressable onPress={onPress} style={[styles.pill,active&&styles.pillActive]}><Text style={[styles.pillText,active&&styles.pillTextActive]}>{label}</Text></Pressable>}
function Btn({label,onPress,secondary=false,disabled=false}:{label:string;onPress:()=>void;secondary?:boolean;disabled?:boolean}){return <Pressable disabled={disabled} onPress={onPress} style={[styles.btn,secondary&&styles.btnSecondary,disabled&&styles.disabled]}><Text style={[styles.btnText,secondary&&styles.btnTextSecondary]}>{label}</Text></Pressable>}

export function OperationsParityScreen({onBack,onOpenWorkOrders}:{onBack:()=>void;onOpenWorkOrders:()=>void}){
 const [tab,setTab]=useState<Tab>('templates');const [snapshot,setSnapshot]=useState<OperationsSnapshot|null>(null);const [equipment,setEquipment]=useState<EquipmentOption[]>([]);const [checklists,setChecklists]=useState<ChecklistTemplate[]>([]);const [loading,setLoading]=useState(true)
 async function load(eq?:string){setLoading(true);try{const [data,eqs,cls]=await Promise.all([loadOperationsParity(eq),listEquipmentOptions(),listChecklistTemplates()]);setSnapshot(data);setEquipment(eqs);setChecklists(cls)}catch(e){Alert.alert('Operations',e instanceof Error?e.message:'Không tải được dữ liệu.')}finally{setLoading(false)}}
 useEffect(()=>{void load()},[])
 return <SafeAreaView style={styles.safe}><View style={styles.header}><Pressable onPress={onBack} style={styles.icon}><Ionicons name="chevron-back" size={26} color="#101828"/></Pressable><View style={styles.copy}><Text style={styles.title}>Operations parity</Text><Text style={styles.sub}>Templates · Portal · Custody · Categories</Text></View><Pressable onPress={()=>void load()} style={styles.icon}><Ionicons name="refresh" size={21} color="#344054"/></Pressable></View><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.tabs}>{TABS.map(x=><Pill key={x.id} active={tab===x.id} label={x.label} onPress={()=>setTab(x.id)}/>)}</ScrollView>{loading?<View style={styles.center}><ActivityIndicator size="large" color="#155EEF"/></View>:<>{tab==='templates'?<Templates snapshot={snapshot} equipment={equipment} checklists={checklists} reload={()=>load()} onOpenWorkOrders={onOpenWorkOrders}/>:null}{tab==='portal'?<Portal snapshot={snapshot} reload={()=>load()}/>:null}{tab==='custody'?<Custody snapshot={snapshot} equipment={equipment} reload={(eq)=>load(eq)}/>:null}{tab==='categories'?<Categories snapshot={snapshot} reload={()=>load()}/>:null}</>}</SafeAreaView>
}

function Templates({snapshot,equipment,checklists,reload,onOpenWorkOrders}:{snapshot:OperationsSnapshot|null;equipment:EquipmentOption[];checklists:ChecklistTemplate[];reload:()=>void;onOpenWorkOrders:()=>void}){
 const [name,setName]=useState('');const [reason,setReason]=useState('');const [priority,setPriority]=useState('MEDIUM');const [checklistId,setChecklistId]=useState('');const [category,setCategory]=useState('');const [equipmentId,setEquipmentId]=useState('');const [templateId,setTemplateId]=useState('');const [busy,setBusy]=useState(false)
 useEffect(()=>{if(!equipmentId&&equipment[0])setEquipmentId(equipment[0].id)},[equipment,equipmentId])
 async function save(){if(!name.trim())return Alert.alert('Thiếu tên template');setBusy(true);try{await saveWorkOrderTemplate({name:name.trim(),reason:reason.trim(),priority,checklistTemplateId:checklistId||undefined,categoryCode:category.trim()||undefined});setName('');setReason('');reload()}catch(e){Alert.alert('Không lưu được',e instanceof Error?e.message:'Lỗi template.')}finally{setBusy(false)}}
 async function create(){if(!templateId||!equipmentId)return Alert.alert('Chọn template và thiết bị');setBusy(true);try{await createWorkOrderFromTemplate(templateId,equipmentId);Alert.alert('Đã tạo Work Order','Checklist/category của template đã được áp dụng.');onOpenWorkOrders()}catch(e){Alert.alert('Không tạo được WO',e instanceof Error?e.message:'Lỗi template.')}finally{setBusy(false)}}
 return <ScrollView contentContainerStyle={styles.body}><View style={styles.card}><Text style={styles.heading}>Tạo template</Text><TextInput value={name} onChangeText={setName} placeholder="Tên template *" style={styles.input}/><TextInput value={reason} onChangeText={setReason} placeholder="Nội dung / lý do mặc định" style={styles.input}/><ScrollView horizontal contentContainerStyle={styles.row}>{['LOW','MEDIUM','HIGH','CRITICAL'].map(x=><Pill key={x} active={priority===x} label={x} onPress={()=>setPriority(x)}/>)}</ScrollView><Text style={styles.label}>Checklist template</Text><ScrollView horizontal contentContainerStyle={styles.row}><Pill active={!checklistId} label="Không" onPress={()=>setChecklistId('')}/>{checklists.map(x=><Pill key={x.templateId} active={checklistId===x.templateId} label={x.name} onPress={()=>setChecklistId(x.templateId)}/>)}</ScrollView><TextInput value={category} onChangeText={setCategory} placeholder="Category code (tùy chọn)" style={styles.input}/><Btn label="Lưu WO template" disabled={busy} onPress={()=>void save()}/></View><Text style={styles.heading}>Tạo WO từ template</Text>{snapshot?.templates.map(t=><Pressable key={t.templateId} onPress={()=>setTemplateId(t.templateId)} style={[styles.listCard,templateId===t.templateId&&styles.selected]}><Text style={styles.listTitle}>{t.name}</Text><Text style={styles.meta}>{t.priority} · {t.categoryCode||'Không category'} · {t.checklistTemplateId?'Có checklist':'Không checklist'}</Text></Pressable>)}<Text style={styles.label}>Thiết bị</Text><ScrollView horizontal contentContainerStyle={styles.row}>{equipment.slice(0,100).map(x=><Pill key={x.id} active={equipmentId===x.id} label={x.name} onPress={()=>setEquipmentId(x.id)}/>)}</ScrollView><Btn label="Tạo Work Order từ template" disabled={busy||!templateId||!equipmentId} onPress={()=>void create()}/></ScrollView>
}

function Portal({snapshot,reload}:{snapshot:OperationsSnapshot|null;reload:()=>void}){
 const p=snapshot?.portal||{};const [name,setName]=useState(String(p.portal_name??p.portalName??'CEV Request Portal'));const [instructions,setInstructions]=useState(String(p.instructions??''));const [enabled,setEnabled]=useState(Boolean(p.enabled??true));const [request,setRequest]=useState(Boolean(p.can_create_request??p.canCreateRequest??true));const [wo,setWo]=useState(Boolean(p.can_create_work_order??p.canCreateWorkOrder??false));const [attachments,setAttachments]=useState(Boolean(p.allow_attachments??p.allowAttachments??true));const [contact,setContact]=useState(Boolean(p.require_contact??p.requireContact??false));const [busy,setBusy]=useState(false)
 async function save(){setBusy(true);try{await saveRequestPortalSettings({settingsId:String(p.settings_id??p.settingsId??'default'),enabled,canCreateRequest:request,canCreateWorkOrder:wo,portalName:name.trim()||'CEV Request Portal',instructions,allowAttachments:attachments,requireContact:contact});Alert.alert('Đã lưu Request Portal');reload()}catch(e){Alert.alert('Không lưu được',e instanceof Error?e.message:'Lỗi portal.')}finally{setBusy(false)}}
 return <ScrollView contentContainerStyle={styles.body}><View style={styles.card}><TextInput value={name} onChangeText={setName} placeholder="Tên portal" style={styles.input}/><TextInput value={instructions} onChangeText={setInstructions} placeholder="Hướng dẫn người gửi yêu cầu" multiline style={[styles.input,styles.multi]}/>{[['Bật portal',enabled,setEnabled],['Cho tạo Request',request,setRequest],['Cho tạo Work Order',wo,setWo],['Cho đính kèm file',attachments,setAttachments],['Bắt buộc thông tin liên hệ',contact,setContact]].map(([label,value,setter])=><View key={String(label)} style={styles.switchRow}><Text style={styles.switchLabel}>{String(label)}</Text><Switch value={Boolean(value)} onValueChange={(v)=>(setter as (v:boolean)=>void)(v)}/></View>)}<Btn label="Lưu Request Portal" disabled={busy} onPress={()=>void save()}/></View></ScrollView>
}

function Custody({snapshot,equipment,reload}:{snapshot:OperationsSnapshot|null;equipment:EquipmentOption[];reload:(eq?:string)=>void}){
 const [equipmentId,setEquipmentId]=useState('');const [holder,setHolder]=useState('');const [note,setNote]=useState('');const [busy,setBusy]=useState(false);useEffect(()=>{if(!equipmentId&&equipment[0])setEquipmentId(equipment[0].id)},[equipment,equipmentId]);const history=useMemo(()=>snapshot?.custody.filter(x=>!equipmentId||x.equipmentId===equipmentId)||[],[snapshot,equipmentId]);const last=history[0];const checkedOut=last?.action==='CHECK_OUT'
 async function change(action:'CHECK_OUT'|'CHECK_IN'){if(!equipmentId)return;setBusy(true);try{await setAssetCustody({equipmentId,action,holderName:holder.trim()||undefined,note:note.trim()});setHolder('');setNote('');await reload(equipmentId)}catch(e){Alert.alert('Custody',e instanceof Error?e.message:'Không cập nhật được.')}finally{setBusy(false)}}
 return <ScrollView contentContainerStyle={styles.body}><Text style={styles.label}>Thiết bị</Text><ScrollView horizontal contentContainerStyle={styles.row}>{equipment.slice(0,100).map(x=><Pill key={x.id} active={equipmentId===x.id} label={x.name} onPress={()=>{setEquipmentId(x.id);reload(x.id)}}/>)}</ScrollView><View style={styles.card}><Text style={[styles.state,checkedOut?styles.out:styles.in]}>{checkedOut?'ĐANG CHECK-OUT':'ĐANG CHECK-IN'}</Text><TextInput value={holder} onChangeText={setHolder} placeholder="Người đang giữ / nhận thiết bị" style={styles.input}/><TextInput value={note} onChangeText={setNote} placeholder="Ghi chú" style={styles.input}/><Btn label={checkedOut?'Check-in thiết bị':'Check-out thiết bị'} disabled={busy} onPress={()=>void change(checkedOut?'CHECK_IN':'CHECK_OUT')}/></View>{history.map(x=><View key={x.custodyEventId} style={styles.listCard}><Text style={styles.listTitle}>{x.action==='CHECK_OUT'?'↗ Check-out':'↙ Check-in'} · {x.holderName||'Không ghi người giữ'}</Text><Text style={styles.meta}>{new Date(x.eventAt).toLocaleString('vi-VN')} · {x.note||'Không ghi chú'}</Text></View>)}</ScrollView>
}

function Categories({snapshot,reload}:{snapshot:OperationsSnapshot|null;reload:()=>void}){
 const [code,setCode]=useState('');const [name,setName]=useState('');const [description,setDescription]=useState('');const [busy,setBusy]=useState(false)
 async function save(){if(!code.trim()||!name.trim())return Alert.alert('Nhập code và tên category');setBusy(true);try{await saveWorkOrderCategory({code:code.trim(),name:name.trim(),description});setCode('');setName('');setDescription('');reload()}catch(e){Alert.alert('Không lưu được',e instanceof Error?e.message:'Lỗi category.')}finally{setBusy(false)}}
 return <ScrollView contentContainerStyle={styles.body}><View style={styles.card}><TextInput value={code} onChangeText={setCode} autoCapitalize="characters" placeholder="Code * (BREAKDOWN, PM...)" style={styles.input}/><TextInput value={name} onChangeText={setName} placeholder="Tên category *" style={styles.input}/><TextInput value={description} onChangeText={setDescription} placeholder="Mô tả" style={styles.input}/><Btn label="Thêm category" disabled={busy} onPress={()=>void save()}/></View>{snapshot?.categories.map(x=><View key={x.categoryId} style={styles.listCard}><Text style={styles.listTitle}>{x.code} · {x.name}</Text><Text style={styles.meta}>{x.description||'Không mô tả'}</Text></View>)}</ScrollView>
}

const styles=StyleSheet.create({safe:{flex:1,backgroundColor:'#F8FAFC'},header:{minHeight:64,paddingHorizontal:8,flexDirection:'row',alignItems:'center',backgroundColor:'#FFF',borderBottomWidth:1,borderBottomColor:'#EAECF0'},icon:{width:46,height:46,alignItems:'center',justifyContent:'center'},copy:{flex:1,alignItems:'center'},title:{fontSize:19,fontWeight:'900',color:'#101828'},sub:{fontSize:11,color:'#667085',marginTop:2},tabs:{padding:10,gap:7,backgroundColor:'#FFF'},pill:{paddingHorizontal:11,paddingVertical:8,borderRadius:18,borderWidth:1,borderColor:'#D0D5DD',backgroundColor:'#FFF'},pillActive:{borderColor:'#155EEF',backgroundColor:'#EEF4FF'},pillText:{fontSize:11.5,fontWeight:'800',color:'#475467'},pillTextActive:{color:'#155EEF'},body:{padding:14,paddingBottom:40},center:{flex:1,alignItems:'center',justifyContent:'center'},card:{padding:14,borderRadius:14,borderWidth:1,borderColor:'#EAECF0',backgroundColor:'#FFF',gap:10,marginBottom:14},heading:{fontSize:16,fontWeight:'900',color:'#101828',marginBottom:8},label:{fontSize:12.5,fontWeight:'800',color:'#475467',marginTop:8,marginBottom:6},input:{minHeight:46,paddingHorizontal:12,borderRadius:10,borderWidth:1,borderColor:'#D0D5DD',backgroundColor:'#FFF',color:'#101828'},multi:{minHeight:92,textAlignVertical:'top',paddingTop:12},row:{gap:7,paddingBottom:8},btn:{minHeight:48,borderRadius:12,backgroundColor:'#155EEF',alignItems:'center',justifyContent:'center',paddingHorizontal:12},btnSecondary:{backgroundColor:'#EEF4FF',borderWidth:1,borderColor:'#B2CCFF'},btnText:{fontSize:13.5,fontWeight:'900',color:'#FFF'},btnTextSecondary:{color:'#155EEF'},disabled:{opacity:.5},listCard:{padding:12,marginBottom:8,borderRadius:12,borderWidth:1,borderColor:'#EAECF0',backgroundColor:'#FFF'},selected:{borderColor:'#155EEF',backgroundColor:'#EEF4FF'},listTitle:{fontSize:13.5,fontWeight:'900',color:'#344054'},meta:{marginTop:3,fontSize:10.5,lineHeight:15,color:'#667085'},switchRow:{minHeight:48,flexDirection:'row',alignItems:'center',justifyContent:'space-between',borderTopWidth:1,borderTopColor:'#F2F4F7'},switchLabel:{fontSize:13,fontWeight:'700',color:'#344054'},state:{fontSize:14,fontWeight:'900'},out:{color:'#B42318'},in:{color:'#027A48'}})
