import { useState } from 'react'
import { ActivityIndicator, Alert, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native'
import { Ionicons } from '@expo/vector-icons'
import { SafeAreaView } from 'react-native-safe-area-context'
import { saveSparePart } from '../features/scan/api/partSearchService'

export function PartFormScreen({ onBack, partId = '', onSaved }: { onBack: () => void; partId?: string; onSaved: (partId: string) => void }) {
  const [form, setForm] = useState({ partName:'', barcode:'', partNumber:'', maker:'', location:'', stockQty:'0', minQty:'0' }); const [saving,setSaving]=useState(false)
  function patch(key: keyof typeof form, value: string) { setForm((current) => ({...current,[key]:value})) }
  async function submit() { if (!form.partName.trim() || saving) return; setSaving(true); try { const part=await saveSparePart({ partId, ...form, stockQty:Number(form.stockQty)||0, minQty:Number(form.minQty)||0 }); Alert.alert('Đã lưu phụ tùng', part.partId, [{text:'Mở chi tiết',onPress:()=>onSaved(part.partId)}]) } catch (error) { Alert.alert('Không thể lưu phụ tùng',error instanceof Error?error.message:'Vui lòng thử lại.')} finally {setSaving(false)} }
  return <SafeAreaView style={styles.safe} edges={['top','bottom']}><View style={styles.header}><Pressable onPress={onBack} style={styles.icon}><Ionicons name="chevron-back" size={26} color="#101828" /></Pressable><Text style={styles.title}>{partId?'Sửa phụ tùng':'Thêm phụ tùng'}</Text><View style={styles.icon}/></View><ScrollView contentContainerStyle={styles.content}><Field label="Tên phụ tùng *" value={form.partName} onChange={(v)=>patch('partName',v)} /><Field label="Barcode" value={form.barcode} onChange={(v)=>patch('barcode',v)} /><Field label="Part number" value={form.partNumber} onChange={(v)=>patch('partNumber',v)} /><Field label="Nhà sản xuất" value={form.maker} onChange={(v)=>patch('maker',v)} /><Field label="Vị trí kho" value={form.location} onChange={(v)=>patch('location',v)} /><View style={styles.two}><View style={styles.flex}><Field label="Tồn kho" value={form.stockQty} onChange={(v)=>patch('stockQty',v)} keyboard="numeric"/></View><View style={styles.flex}><Field label="Tối thiểu" value={form.minQty} onChange={(v)=>patch('minQty',v)} keyboard="numeric"/></View></View></ScrollView><View style={styles.bottom}><Pressable disabled={!form.partName.trim()||saving} onPress={()=>void submit()} style={[styles.submit,(!form.partName.trim()||saving)&&styles.disabled]}>{saving?<ActivityIndicator color="#FFF"/>:<Text style={styles.submitText}>Lưu phụ tùng</Text>}</Pressable></View></SafeAreaView>
}
function Field({label,value,onChange,keyboard}:{label:string;value:string;onChange:(v:string)=>void;keyboard?:'numeric'}) { return <View style={styles.field}><Text style={styles.label}>{label}</Text><TextInput value={value} onChangeText={onChange} keyboardType={keyboard} style={styles.input}/></View> }
const styles=StyleSheet.create({safe:{flex:1,backgroundColor:'#F8F9FB'},header:{minHeight:60,paddingHorizontal:8,flexDirection:'row',alignItems:'center',justifyContent:'space-between',backgroundColor:'#FFF'},icon:{width:46,height:46,alignItems:'center',justifyContent:'center'},title:{fontSize:20,fontWeight:'900',color:'#101828'},content:{padding:16},field:{marginBottom:14},label:{marginBottom:7,fontSize:13,fontWeight:'900',color:'#344054'},input:{minHeight:48,paddingHorizontal:13,borderRadius:11,borderWidth:1,borderColor:'#D0D5DD',backgroundColor:'#FFF',fontSize:15,color:'#101828'},two:{flexDirection:'row',gap:12},flex:{flex:1},bottom:{padding:16,backgroundColor:'#FFF',borderTopWidth:StyleSheet.hairlineWidth,borderTopColor:'#EAECF0'},submit:{minHeight:52,borderRadius:26,alignItems:'center',justifyContent:'center',backgroundColor:'#155EEF'},disabled:{opacity:.45},submitText:{fontSize:16,fontWeight:'900',color:'#FFF'}})
