import { useEffect, useState } from 'react'
import { ActivityIndicator, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native'
import { Ionicons } from '@expo/vector-icons'
import { SafeAreaView } from 'react-native-safe-area-context'
import { getSparePart, listSparePartUsage, type SparePart } from '../features/scan/api/partSearchService'

export function PartInventoryScreen({ partId, onBack }: { partId: string; onBack: () => void }) {
  const [part, setPart] = useState<SparePart | null>(null); const [usage, setUsage] = useState<Array<Record<string, unknown>>>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState('')
  useEffect(() => { let active = true; Promise.all([getSparePart(partId), listSparePartUsage(partId)]).then(([p,u]) => { if (active) { setPart(p); setUsage(u) } }).catch((reason) => { if (active) setError(reason instanceof Error ? reason.message : 'Không tải được tồn kho.') }).finally(() => { if (active) setLoading(false) }); return () => { active = false } }, [partId])
  return <SafeAreaView style={styles.safe} edges={['top', 'bottom']}><View style={styles.header}><Pressable onPress={onBack} style={styles.icon}><Ionicons name="chevron-back" size={26} color="#101828" /></Pressable><Text style={styles.title}>Tồn kho phụ tùng</Text><View style={styles.icon} /></View>{loading ? <View style={styles.center}><ActivityIndicator color="#155EEF" /></View> : error ? <View style={styles.center}><Text>{error}</Text></View> : <ScrollView contentContainerStyle={styles.content}><View style={styles.stock}><Text style={styles.part}>{part?.partId} · {part?.partName}</Text><Text style={styles.qty}>{part?.stockQty ?? 0}</Text><Text style={styles.caption}>Số lượng hiện tại · Tối thiểu {part?.minQty ?? 0}</Text></View><Text style={styles.heading}>Lịch sử sử dụng</Text>{usage.length ? usage.map((item, index) => <View key={`${String(item.usage_id)}:${index}`} style={styles.row}><Text style={styles.rowTitle}>{String(item.equipment_id || '—')}</Text><Text style={styles.rowMeta}>Dùng {String(item.quantity || 0)} · {String(item.work_order_id || 'Không gắn WO')}</Text></View>) : <Text style={styles.empty}>Chưa có lịch sử sử dụng.</Text>}</ScrollView>}</SafeAreaView>
}
const styles = StyleSheet.create({ safe:{flex:1,backgroundColor:'#F8F9FB'},header:{minHeight:60,paddingHorizontal:8,flexDirection:'row',alignItems:'center',justifyContent:'space-between',backgroundColor:'#FFF',borderBottomWidth:StyleSheet.hairlineWidth,borderBottomColor:'#EAECF0'},icon:{width:46,height:46,alignItems:'center',justifyContent:'center'},title:{fontSize:20,fontWeight:'900',color:'#101828'},center:{flex:1,alignItems:'center',justifyContent:'center',padding:24},content:{padding:16},stock:{padding:18,borderRadius:16,backgroundColor:'#EFF4FF'},part:{fontSize:15,fontWeight:'900',color:'#155EEF'},qty:{marginTop:10,fontSize:36,fontWeight:'900',color:'#101828'},caption:{marginTop:2,fontSize:12,color:'#667085'},heading:{marginTop:22,marginBottom:8,fontSize:15,fontWeight:'900',color:'#344054'},row:{padding:13,marginBottom:8,borderRadius:12,backgroundColor:'#FFF'},rowTitle:{fontSize:14,fontWeight:'900',color:'#344054'},rowMeta:{marginTop:4,fontSize:12,color:'#667085'},empty:{color:'#667085'} })
