import { useEffect, useState } from 'react'
import { ActivityIndicator, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native'
import { Ionicons } from '@expo/vector-icons'
import { SafeAreaView } from 'react-native-safe-area-context'
import { getSparePart, type SparePart } from '../features/scan/api/partSearchService'

export function PartDetailsScreen({ partId, onBack }: { partId: string; onBack: () => void }) {
  const [part, setPart] = useState<SparePart | null>(null)
  const [error, setError] = useState('')
  useEffect(() => { let active = true; void getSparePart(partId).then((value) => { if (active) setPart(value) }).catch((reason) => { if (active) setError(reason instanceof Error ? reason.message : 'Không tải được phụ tùng.') }); return () => { active = false } }, [partId])
  return <SafeAreaView style={styles.safe} edges={['top', 'bottom']}><View style={styles.header}><Pressable onPress={onBack} style={styles.icon}><Ionicons name="chevron-back" size={26} color="#101828" /></Pressable><Text style={styles.title}>Chi tiết phụ tùng</Text><View style={styles.icon} /></View>{!part && !error ? <View style={styles.center}><ActivityIndicator color="#155EEF" /></View> : error ? <View style={styles.center}><Text style={styles.error}>{error}</Text></View> : <ScrollView contentContainerStyle={styles.content}><View style={styles.hero}><Ionicons name="cube-outline" size={32} color="#155EEF" /><Text style={styles.partId}>{part?.partId}</Text><Text style={styles.name}>{part?.partName}</Text></View><Info label="Barcode" value={part?.barcode || 'Chưa có'} /><Info label="Part number" value={part?.partNumber || '—'} /><Info label="Nhà sản xuất" value={part?.maker || '—'} /><Info label="Vị trí kho" value={part?.location || '—'} /><Info label="Tồn kho" value={`${part?.stockQty ?? 0} · Tối thiểu ${part?.minQty ?? 0}`} /><Info label="Phân loại" value={part?.classification || 'NORMAL'} /></ScrollView>}</SafeAreaView>
}
function Info({ label, value }: { label: string; value: string }) { return <View style={styles.info}><Text style={styles.label}>{label}</Text><Text style={styles.value}>{value}</Text></View> }
const styles = StyleSheet.create({ safe:{flex:1,backgroundColor:'#F1F1FA'},header:{minHeight:60,paddingHorizontal:8,flexDirection:'row',alignItems:'center',justifyContent:'space-between',backgroundColor:'#FFF',borderBottomWidth:StyleSheet.hairlineWidth,borderBottomColor:'#E5E5EF'},icon:{width:46,height:46,alignItems:'center',justifyContent:'center'},title:{fontSize:20,fontWeight:'900',color:'#101828'},center:{flex:1,alignItems:'center',justifyContent:'center',padding:24},error:{color:'#B42318',textAlign:'center'},content:{padding:14},hero:{padding:20,alignItems:'center',borderRadius:18,backgroundColor:'#E9EDFF'},partId:{marginTop:9,fontSize:14,fontWeight:'900',color:'#155EEF'},name:{marginTop:5,fontSize:20,fontWeight:'900',color:'#101828',textAlign:'center'},info:{marginTop:10,padding:15,borderRadius:17,backgroundColor:'#FFF',borderWidth:StyleSheet.hairlineWidth,borderColor:'#E1E1EA'},label:{fontSize:12,fontWeight:'800',color:'#667085'},value:{marginTop:5,fontSize:15,fontWeight:'800',color:'#344054'} })
