import { useEffect, useMemo, useState } from 'react'
import { ActivityIndicator, FlatList, Pressable, StyleSheet, Text, TextInput, View } from 'react-native'
import { Ionicons } from '@expo/vector-icons'
import { SafeAreaView } from 'react-native-safe-area-context'
import { listSpareParts, type SparePart } from '../features/scan/api/partSearchService'

export function PartsListScreen({ onBack, onScan, onCreate, onOpenPart }: { onBack: () => void; onScan: () => void; onCreate: () => void; onOpenPart: (partId: string) => void }) {
  const [items, setItems] = useState<SparePart[]>([]); const [query, setQuery] = useState(''); const [loading, setLoading] = useState(true); const [error, setError] = useState('')
  useEffect(() => { let active = true; void listSpareParts().then((next) => { if (active) setItems(next) }).catch((reason) => { if (active) setError(reason instanceof Error ? reason.message : 'Không tải được phụ tùng.') }).finally(() => { if (active) setLoading(false) }); return () => { active = false } }, [])
  const filtered = useMemo(() => { const q = query.trim().toLocaleLowerCase('vi'); return q ? items.filter((p) => [p.partId,p.partName,p.barcode,p.partNumber,p.maker].some((v) => v.toLocaleLowerCase('vi').includes(q))) : items }, [items, query])
  return <SafeAreaView style={styles.safe} edges={['top','bottom']}><View style={styles.header}><Pressable onPress={onBack} style={styles.icon}><Ionicons name="chevron-back" size={26} color="#101828" /></Pressable><Text style={styles.title}>Phụ tùng</Text><View style={styles.actions}><Pressable onPress={onScan} style={styles.small}><Ionicons name="scan-outline" size={21} color="#155EEF" /></Pressable><Pressable onPress={onCreate} style={styles.small}><Ionicons name="add" size={25} color="#155EEF" /></Pressable></View></View><View style={styles.search}><Ionicons name="search-outline" size={19} color="#98A2B3" /><TextInput value={query} onChangeText={setQuery} placeholder="Tìm phụ tùng, barcode..." placeholderTextColor="#98A2B3" style={styles.input} /></View>{error ? <Text style={styles.error}>{error}</Text> : loading ? <View style={styles.center}><ActivityIndicator color="#155EEF" /></View> : <FlatList data={filtered} keyExtractor={(item) => item.partId} contentContainerStyle={styles.list} renderItem={({item}) => <Pressable onPress={() => onOpenPart(item.partId)} style={styles.row}><View style={styles.partIcon}><Ionicons name="cube-outline" size={21} color="#7F56D9" /></View><View style={styles.copy}><Text style={styles.id}>{item.partId}</Text><Text style={styles.name}>{item.partName}</Text><Text style={styles.meta}>{item.barcode || item.partNumber || 'Chưa có barcode'} · Tồn {item.stockQty}</Text></View><Ionicons name="chevron-forward" size={20} color="#98A2B3" /></Pressable>} ListEmptyComponent={<View style={styles.center}><Text style={styles.empty}>Chưa có phụ tùng phù hợp.</Text></View>} />}</SafeAreaView>
}
const styles=StyleSheet.create({safe:{flex:1,backgroundColor:'#F8F9FB'},header:{minHeight:60,paddingHorizontal:8,flexDirection:'row',alignItems:'center',justifyContent:'space-between',backgroundColor:'#FFF',borderBottomWidth:StyleSheet.hairlineWidth,borderBottomColor:'#EAECF0'},icon:{width:46,height:46,alignItems:'center',justifyContent:'center'},actions:{flexDirection:'row',gap:2},small:{width:42,height:42,alignItems:'center',justifyContent:'center'},title:{fontSize:20,fontWeight:'900',color:'#101828'},search:{margin:12,paddingHorizontal:12,minHeight:46,flexDirection:'row',alignItems:'center',gap:8,borderRadius:12,borderWidth:1,borderColor:'#D0D5DD',backgroundColor:'#FFF'},input:{flex:1,fontSize:14,color:'#101828'},list:{padding:12,gap:8},row:{padding:13,flexDirection:'row',alignItems:'center',gap:10,borderRadius:14,backgroundColor:'#FFF'},partIcon:{width:42,height:42,borderRadius:21,alignItems:'center',justifyContent:'center',backgroundColor:'#F3E8FF'},copy:{flex:1},id:{fontSize:12,fontWeight:'900',color:'#155EEF'},name:{marginTop:2,fontSize:15,fontWeight:'800',color:'#344054'},meta:{marginTop:4,fontSize:11.5,color:'#667085'},center:{flex:1,alignItems:'center',justifyContent:'center',padding:24},empty:{color:'#667085'},error:{margin:16,color:'#B42318'}})
