import { useEffect, useMemo, useState } from 'react'
import { ActivityIndicator, FlatList, Pressable, RefreshControl, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native'
import { Ionicons } from '@expo/vector-icons'
import { SafeAreaView } from 'react-native-safe-area-context'
import { listMaintenanceRequests, type MaintenanceRequest } from '../features/requests/requestService'

function statusLabel(value: string) { const v=value.toUpperCase(); if(v==='OPEN') return 'Mở'; if(v==='IN_PROGRESS') return 'Đang xử lý'; if(v==='COMPLETED') return 'Hoàn thành'; return value||'Chưa có trạng thái' }
function dateLabel(value: string) { const d=new Date(value); return Number.isNaN(d.getTime())?'—':new Intl.DateTimeFormat('vi-VN',{day:'2-digit',month:'2-digit',year:'numeric'}).format(d) }
export function RequestsScreen({ onBack, equipmentId, onOpenRequest }: { onBack:()=>void; equipmentId?:string; onOpenRequest: (requestId: string) => void }) {
 const [items,setItems]=useState<MaintenanceRequest[]>([]); const [query,setQuery]=useState(''); const [selectedStatus,setSelectedStatus]=useState('ALL'); const [loading,setLoading]=useState(true); const [refreshing,setRefreshing]=useState(false); const [error,setError]=useState('')
 async function load(force=false){if(force)setRefreshing(true);setError('');try{setItems(await listMaintenanceRequests())}catch(reason){setError(reason instanceof Error?reason.message:'Không tải được yêu cầu.')}finally{setLoading(false);setRefreshing(false)}}
 useEffect(()=>{void load()},[])
 const filtered=useMemo(()=>{const q=query.trim().toLocaleLowerCase('vi');return items.filter(i=>{const status=i.status.toUpperCase();return (!equipmentId||i.equipmentId===equipmentId)&&(selectedStatus==='ALL'||status===selectedStatus)&&(!q||[i.requestId,i.equipmentId,i.reason,i.createdBy].some(v=>v.toLocaleLowerCase('vi').includes(q)))})},[equipmentId,items,query,selectedStatus])
 const statuses=[['ALL','Tất cả'],['OPEN','Mở'],['IN_PROGRESS','Đang xử lý'],['COMPLETED','Hoàn thành']] as const
 return <SafeAreaView style={styles.safe} edges={['top','bottom']}><View style={styles.header}><Pressable onPress={onBack} style={styles.icon}><Ionicons name="chevron-back" size={26} color="#101828"/></Pressable><Text style={styles.title}>{equipmentId?'Yêu cầu của thiết bị':'Yêu cầu'}</Text><Pressable onPress={()=>{setSelectedStatus('ALL');setQuery('')}} style={styles.icon}><Ionicons name="options-outline" size={22} color="#667085"/></Pressable></View><View style={styles.toolbar}><View style={styles.search}><Ionicons name="search-outline" size={19} color="#98A2B3"/><TextInput value={query} onChangeText={setQuery} placeholder="Tìm yêu cầu, thiết bị..." placeholderTextColor="#98A2B3" style={styles.input}/>{query?<Pressable onPress={()=>setQuery('')}><Ionicons name="close-circle" size={18} color="#98A2B3"/></Pressable>:null}</View><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.filters}>{statuses.map(([value,label])=><Pressable key={value} onPress={()=>setSelectedStatus(value)} style={[styles.filter,selectedStatus===value&&styles.filterActive]}><Text style={[styles.filterText,selectedStatus===value&&styles.filterTextActive]}>{label}</Text></Pressable>)}</ScrollView><Text style={styles.counter}>{filtered.length} yêu cầu</Text></View>{error?<View style={styles.errorBox}><Text style={styles.error}>{error}</Text></View>:null}{loading?<View style={styles.center}><ActivityIndicator color="#536DFE"/></View>:<FlatList data={filtered} keyExtractor={i=>i.requestId} refreshControl={<RefreshControl refreshing={refreshing} onRefresh={()=>void load(true)} tintColor="#536DFE"/>} contentContainerStyle={filtered.length?styles.list:styles.emptyList} renderItem={({item})=><Pressable onPress={()=>onOpenRequest(item.requestId)} style={({pressed})=>[styles.card,pressed&&styles.cardPressed]}><View style={styles.cardTop}><View style={styles.idLine}><View style={styles.statusDot}/><Text style={styles.id}>{item.requestId}</Text></View><Ionicons name="chevron-forward" size={20} color="#98A2B3"/></View><Text style={styles.reason} numberOfLines={2}>{item.reason||'Không có nội dung'}</Text><View style={styles.badge}><Text style={styles.status}>{statusLabel(item.status)}</Text></View><View style={styles.metaRow}><Ionicons name="cube-outline" size={15} color="#667085"/><Text style={styles.metaText} numberOfLines={1}>{item.equipmentId||'Chưa gắn thiết bị'}</Text></View><View style={styles.metaBottom}><Text style={styles.subtle}>{item.createdBy||'Không rõ người gửi'}</Text><Text style={styles.subtle}>{dateLabel(item.createdAt)}</Text></View></Pressable>} ListEmptyComponent={<View style={styles.center}><Ionicons name="chatbox-ellipses-outline" size={42} color="#98A2B3"/><Text style={styles.empty}>Chưa có yêu cầu phù hợp</Text><Text style={styles.emptyHint}>Thử thay đổi từ khóa hoặc bộ lọc.</Text></View>}/>}</SafeAreaView>
}
const styles=StyleSheet.create({safe:{flex:1,backgroundColor:'#F1F1FA'},header:{minHeight:60,paddingHorizontal:8,flexDirection:'row',alignItems:'center',justifyContent:'space-between',backgroundColor:'#FFF',borderBottomWidth:StyleSheet.hairlineWidth,borderBottomColor:'#E5E5EF'},icon:{width:46,height:46,alignItems:'center',justifyContent:'center'},title:{fontSize:20,fontWeight:'900',color:'#101828'},toolbar:{paddingHorizontal:14,paddingTop:12,paddingBottom:9,backgroundColor:'#FFF'},search:{paddingHorizontal:12,minHeight:46,flexDirection:'row',alignItems:'center',gap:8,borderRadius:23,borderWidth:1,borderColor:'#D7D8E5',backgroundColor:'#FFF'},input:{flex:1,minHeight:44,fontSize:14,color:'#101828'},filters:{paddingTop:11,paddingBottom:6,gap:8},filter:{minHeight:35,paddingHorizontal:15,alignItems:'center',justifyContent:'center',borderRadius:18,borderWidth:1,borderColor:'#D9DAE7',backgroundColor:'#FFF'},filterActive:{borderColor:'#536DFE',backgroundColor:'#536DFE'},filterText:{fontSize:12.5,fontWeight:'700',color:'#475467'},filterTextActive:{color:'#FFF'},counter:{fontSize:12,fontWeight:'800',color:'#667085'},errorBox:{margin:14,padding:12,borderRadius:10,backgroundColor:'#FEF3F2'},error:{color:'#B42318',fontSize:13},list:{padding:14,gap:11},emptyList:{flexGrow:1},card:{padding:16,borderRadius:18,backgroundColor:'#FFF',borderWidth:StyleSheet.hairlineWidth,borderColor:'#E1E1EA',shadowColor:'#28324D',shadowOpacity:.04,shadowRadius:7,shadowOffset:{width:0,height:2},elevation:1},cardPressed:{backgroundColor:'#F9FAFB'},cardTop:{flexDirection:'row',alignItems:'center',justifyContent:'space-between',gap:8},idLine:{flex:1,flexDirection:'row',alignItems:'center',gap:8},statusDot:{width:8,height:8,borderRadius:4,backgroundColor:'#536DFE'},id:{fontSize:13,fontWeight:'900',color:'#155EEF'},reason:{marginTop:10,fontSize:16,lineHeight:21,fontWeight:'900',color:'#1D2939'},badge:{alignSelf:'flex-start',marginTop:11,paddingHorizontal:9,paddingVertical:5,borderRadius:10,backgroundColor:'#E9F0FF'},status:{fontSize:10.5,fontWeight:'800',color:'#344054'},metaRow:{marginTop:11,flexDirection:'row',alignItems:'center',gap:6},metaText:{flex:1,fontSize:12.5,color:'#475467'},metaBottom:{marginTop:10,paddingTop:9,flexDirection:'row',justifyContent:'space-between',gap:8,borderTopWidth:StyleSheet.hairlineWidth,borderTopColor:'#EAECF0'},subtle:{fontSize:11.5,color:'#98A2B3'},center:{flex:1,alignItems:'center',justifyContent:'center',padding:24},empty:{marginTop:9,fontSize:15,fontWeight:'900',color:'#344054'},emptyHint:{marginTop:5,fontSize:12.5,color:'#667085'}})
