import { useEffect, useState } from 'react'
import { ActivityIndicator, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native'
import { Ionicons } from '@expo/vector-icons'
import { SafeAreaView } from 'react-native-safe-area-context'
import { getMaintenanceRequest, transitionMaintenanceRequest } from '../features/requests/requestService'

export function RequestDetailScreen({ requestId, onBack }: { requestId: string; onBack: () => void }) {
 const [item,setItem]=useState<Awaited<ReturnType<typeof getMaintenanceRequest>>|null>(null); const [error,setError]=useState(''); const [saving,setSaving]=useState(false)
 useEffect(()=>{let active=true;void getMaintenanceRequest(requestId).then(v=>{if(active)setItem(v)}).catch(e=>{if(active)setError(e instanceof Error?e.message:'Không tải được yêu cầu.')});return()=>{active=false}},[requestId])
 async function changeStatus(status: 'IN_PROGRESS'|'COMPLETED'|'CANCELLED') { if(!item||saving)return; setSaving(true); try { await transitionMaintenanceRequest(item.requestId,status); setItem({...item,status}) } catch(e) { setError(e instanceof Error?e.message:'Không cập nhật được trạng thái.') } finally {setSaving(false)} }
 return <SafeAreaView style={styles.safe} edges={['top','bottom']}><View style={styles.header}><Pressable onPress={onBack} style={styles.icon}><Ionicons name="chevron-back" size={26} color="#101828"/></Pressable><Text style={styles.title}>Chi tiết yêu cầu</Text><View style={styles.icon}/></View>{!item&&!error?<View style={styles.center}><ActivityIndicator color="#155EEF"/></View>:error?<View style={styles.center}><Text style={styles.error}>{error}</Text></View>:<ScrollView contentContainerStyle={styles.content}><View style={styles.hero}><Ionicons name="chatbox-ellipses-outline" size={29} color="#155EEF"/><Text style={styles.id}>{item?.requestId}</Text><Text style={styles.status}>{item?.status==='OPEN'?'Mở':item?.status}</Text></View><Info label="Thiết bị" value={item?.equipmentId||'—'}/><Info label="Nội dung" value={item?.reason||'—'}/><Info label="Nguồn tạo" value={item?.sourceType||'—'}/><Info label="Mã quét" value={item?.sourceId||'—'}/><Info label="Người tạo" value={item?.createdBy||'—'}/><Info label="Ngày tạo" value={item?.createdAt||'—'}/>{item?.status==='OPEN'?<Pressable disabled={saving} onPress={()=>void changeStatus('IN_PROGRESS')} style={styles.primary}><Text style={styles.primaryText}>Bắt đầu xử lý</Text></Pressable>:null}{item?.status==='IN_PROGRESS'?<Pressable disabled={saving} onPress={()=>void changeStatus('COMPLETED')} style={styles.primary}><Text style={styles.primaryText}>Đánh dấu hoàn thành</Text></Pressable>:null}{item?.status!=='COMPLETED'&&item?.status!=='CANCELLED'?<Pressable disabled={saving} onPress={()=>void changeStatus('CANCELLED')} style={styles.cancel}><Text style={styles.cancelText}>Hủy yêu cầu</Text></Pressable>:null}</ScrollView>}</SafeAreaView>
}
function Info({label,value}:{label:string;value:string}){return <View style={styles.info}><Text style={styles.label}>{label}</Text><Text style={styles.value}>{value}</Text></View>}
const styles=StyleSheet.create({safe:{flex:1,backgroundColor:'#F1F1FA'},header:{minHeight:60,paddingHorizontal:8,flexDirection:'row',alignItems:'center',justifyContent:'space-between',backgroundColor:'#FFF',borderBottomWidth:StyleSheet.hairlineWidth,borderBottomColor:'#E5E5EF'},icon:{width:46,height:46,alignItems:'center',justifyContent:'center'},title:{fontSize:20,fontWeight:'900',color:'#101828'},center:{flex:1,alignItems:'center',justifyContent:'center',padding:24},error:{color:'#B42318'},content:{padding:14,paddingBottom:30},hero:{padding:20,alignItems:'center',borderRadius:18,backgroundColor:'#E9EDFF'},id:{marginTop:8,fontSize:15,fontWeight:'900',color:'#155EEF'},status:{marginTop:7,paddingHorizontal:10,paddingVertical:5,borderRadius:10,fontSize:12,fontWeight:'900',color:'#344054',backgroundColor:'#FFF'},info:{marginTop:10,padding:15,borderRadius:17,backgroundColor:'#FFF',borderWidth:StyleSheet.hairlineWidth,borderColor:'#E1E1EA'},label:{fontSize:12,fontWeight:'800',color:'#667085'},value:{marginTop:5,fontSize:15,fontWeight:'800',color:'#344054'},primary:{marginTop:18,minHeight:52,borderRadius:26,alignItems:'center',justifyContent:'center',backgroundColor:'#536DFE'},primaryText:{fontSize:15,fontWeight:'900',color:'#FFF'},cancel:{marginTop:8,minHeight:45,alignItems:'center',justifyContent:'center'},cancelText:{fontSize:14,fontWeight:'800',color:'#B42318'}})
