import { useEffect, useState } from 'react'
import { ActivityIndicator, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native'
import { Ionicons } from '@expo/vector-icons'
import { SafeAreaView } from 'react-native-safe-area-context'
import { getMaintenanceRequest } from '../features/requests/requestService'

export function RequestDetailScreen({ requestId, onBack }: { requestId: string; onBack: () => void }) {
 const [item,setItem]=useState<Awaited<ReturnType<typeof getMaintenanceRequest>>|null>(null); const [error,setError]=useState('')
 useEffect(()=>{let active=true;void getMaintenanceRequest(requestId).then(v=>{if(active)setItem(v)}).catch(e=>{if(active)setError(e instanceof Error?e.message:'Không tải được yêu cầu.')});return()=>{active=false}},[requestId])
 return <SafeAreaView style={styles.safe} edges={['top','bottom']}><View style={styles.header}><Pressable onPress={onBack} style={styles.icon}><Ionicons name="chevron-back" size={26} color="#101828"/></Pressable><Text style={styles.title}>Chi tiết yêu cầu</Text><View style={styles.icon}/></View>{!item&&!error?<View style={styles.center}><ActivityIndicator color="#155EEF"/></View>:error?<View style={styles.center}><Text style={styles.error}>{error}</Text></View>:<ScrollView contentContainerStyle={styles.content}><View style={styles.hero}><Ionicons name="chatbox-ellipses-outline" size={29} color="#155EEF"/><Text style={styles.id}>{item?.requestId}</Text><Text style={styles.status}>{item?.status==='OPEN'?'Mở':item?.status}</Text></View><Info label="Thiết bị" value={item?.equipmentId||'—'}/><Info label="Nội dung" value={item?.reason||'—'}/><Info label="Nguồn tạo" value={item?.sourceType||'—'}/><Info label="Mã quét" value={item?.sourceId||'—'}/><Info label="Người tạo" value={item?.createdBy||'—'}/><Info label="Ngày tạo" value={item?.createdAt||'—'}/></ScrollView>}</SafeAreaView>
}
function Info({label,value}:{label:string;value:string}){return <View style={styles.info}><Text style={styles.label}>{label}</Text><Text style={styles.value}>{value}</Text></View>}
const styles=StyleSheet.create({safe:{flex:1,backgroundColor:'#F8F9FB'},header:{minHeight:60,paddingHorizontal:8,flexDirection:'row',alignItems:'center',justifyContent:'space-between',backgroundColor:'#FFF',borderBottomWidth:StyleSheet.hairlineWidth,borderBottomColor:'#EAECF0'},icon:{width:46,height:46,alignItems:'center',justifyContent:'center'},title:{fontSize:20,fontWeight:'900',color:'#101828'},center:{flex:1,alignItems:'center',justifyContent:'center',padding:24},error:{color:'#B42318'},content:{padding:16},hero:{padding:18,alignItems:'center',borderRadius:16,backgroundColor:'#EFF4FF'},id:{marginTop:8,fontSize:15,fontWeight:'900',color:'#155EEF'},status:{marginTop:5,fontSize:14,fontWeight:'800',color:'#475467'},info:{marginTop:10,padding:14,borderRadius:12,backgroundColor:'#FFF',borderWidth:StyleSheet.hairlineWidth,borderColor:'#DDE1E7'},label:{fontSize:12,fontWeight:'800',color:'#667085'},value:{marginTop:4,fontSize:15,fontWeight:'800',color:'#344054'}})
