import { useMemo, useState } from 'react'
import { ActivityIndicator, FlatList, Modal, Pressable, StyleSheet, Text, TextInput, View } from 'react-native'
import { Ionicons } from '@expo/vector-icons'
import { SafeAreaView } from 'react-native-safe-area-context'

export type LiveSelectionItem = { id: string; title: string; subtitle?: string; meta?: string }

export function LiveSelectionModal({ visible, title, items, selectedId, loading, error, onClose, onSelect }: { visible: boolean; title: string; items: LiveSelectionItem[]; selectedId?: string | null; loading?: boolean; error?: string; onClose: () => void; onSelect: (item: LiveSelectionItem) => void }) {
  const [query, setQuery] = useState('')
  const filtered = useMemo(() => {
    const q = query.trim().toLocaleLowerCase('vi')
    if (!q) return items
    return items.filter((item) => `${item.title} ${item.subtitle || ''} ${item.meta || ''}`.toLocaleLowerCase('vi').includes(q))
  }, [items, query])
  return <Modal visible={visible} animationType="slide" onRequestClose={onClose}><SafeAreaView style={styles.safe} edges={['top','bottom']}><View style={styles.header}><Pressable onPress={onClose} style={styles.icon}><Ionicons name="close" size={27} color="#101828" /></Pressable><Text style={styles.title}>{title}</Text><View style={styles.icon}/></View><View style={styles.search}><Ionicons name="search-outline" size={22} color="#667085"/><TextInput value={query} onChangeText={setQuery} placeholder="Tìm kiếm" placeholderTextColor="#98A2B3" autoCorrect={false} style={styles.searchInput}/></View>{loading ? <View style={styles.center}><ActivityIndicator/><Text style={styles.centerText}>Đang tải dữ liệu thật...</Text></View> : error ? <View style={styles.center}><Ionicons name="alert-circle-outline" size={28} color="#B42318"/><Text style={styles.error}>{error}</Text></View> : <FlatList data={filtered} keyExtractor={(item)=>item.id} keyboardShouldPersistTaps="handled" renderItem={({item})=>{const active=item.id===selectedId;return <Pressable onPress={()=>onSelect(item)} style={styles.row}><View style={styles.avatar}><Text style={styles.avatarText}>{item.title.trim().split(/\s+/).slice(0,2).map((part)=>part[0]||'').join('').toUpperCase()||'—'}</Text></View><View style={styles.copy}><Text style={styles.name}>{item.title}</Text>{item.subtitle?<Text style={styles.sub}>{item.subtitle}</Text>:null}{item.meta?<Text style={styles.meta}>{item.meta}</Text>:null}</View>{active?<Ionicons name="checkmark-circle" size={25} color="#155EEF"/>:<Ionicons name="ellipse-outline" size={25} color="#D0D5DD"/>}</Pressable>}} ListEmptyComponent={<View style={styles.center}><Text style={styles.centerText}>Không có dữ liệu phù hợp.</Text></View>}/>}</SafeAreaView></Modal>
}

const styles=StyleSheet.create({safe:{flex:1,backgroundColor:'#FFF'},header:{minHeight:60,paddingHorizontal:8,flexDirection:'row',alignItems:'center',borderBottomWidth:StyleSheet.hairlineWidth,borderBottomColor:'#EAECF0'},icon:{width:46,height:46,alignItems:'center',justifyContent:'center'},title:{flex:1,textAlign:'center',fontSize:20,fontWeight:'900',color:'#101828'},search:{margin:14,minHeight:50,paddingHorizontal:13,flexDirection:'row',alignItems:'center',gap:8,borderRadius:14,backgroundColor:'#F2F4F7'},searchInput:{flex:1,fontSize:15,color:'#101828'},row:{minHeight:72,paddingHorizontal:16,flexDirection:'row',alignItems:'center',gap:12,borderBottomWidth:StyleSheet.hairlineWidth,borderBottomColor:'#EAECF0'},avatar:{width:42,height:42,borderRadius:21,alignItems:'center',justifyContent:'center',backgroundColor:'#E9EDFF'},avatarText:{fontSize:13,fontWeight:'900',color:'#344054'},copy:{flex:1,minWidth:0},name:{fontSize:15.5,fontWeight:'900',color:'#101828'},sub:{marginTop:3,fontSize:12.5,color:'#667085'},meta:{marginTop:2,fontSize:11.5,color:'#98A2B3'},center:{padding:32,alignItems:'center',gap:8},centerText:{fontSize:13,color:'#667085',textAlign:'center'},error:{fontSize:13,color:'#B42318',textAlign:'center'}})
