-- Core parity big block: checklist templates, custom fields, file library, floor plans, downtime UX RPCs.
create table if not exists public.cmms_custom_field_definition (
  field_id uuid primary key default gen_random_uuid(),
  entity_type text not null check (entity_type in ('ASSET','WORK_ORDER','PART','LOCATION','METER','VENDOR','CUSTOMER')),
  label text not null,
  field_type text not null default 'TEXT' check (field_type in ('TEXT','NUMBER','DATE','BOOLEAN','SELECT','MULTI_SELECT')),
  required boolean not null default false,
  choices jsonb not null default '[]'::jsonb,
  active boolean not null default true,
  sort_order integer not null default 0,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create unique index if not exists cmms_custom_field_definition_name_uq on public.cmms_custom_field_definition(entity_type,lower(label)) where active;
create table if not exists public.cmms_custom_field_value (
  value_id uuid primary key default gen_random_uuid(),
  field_id uuid not null references public.cmms_custom_field_definition(field_id) on delete cascade,
  entity_type text not null,
  entity_id text not null,
  value jsonb,
  updated_by uuid references auth.users(id) on delete set null,
  updated_at timestamptz not null default now(),
  unique(field_id,entity_id)
);
create table if not exists public.cmms_file_library (
  file_id uuid primary key default gen_random_uuid(), file_name text not null,
  storage_bucket text not null default 'work-order-attachments', storage_path text not null,
  mime_type text, file_size_bytes bigint, description text, tags text[] not null default '{}', archived_at timestamptz,
  created_by uuid references auth.users(id) on delete set null, created_at timestamptz not null default now(), updated_at timestamptz not null default now(),
  unique(storage_bucket,storage_path)
);
create table if not exists public.cmms_file_link (
  link_id uuid primary key default gen_random_uuid(), file_id uuid not null references public.cmms_file_library(file_id) on delete cascade,
  entity_type text not null check(entity_type in ('ASSET','WORK_ORDER','PART','LOCATION')), entity_id text not null,
  created_by uuid references auth.users(id) on delete set null, created_at timestamptz not null default now(), unique(file_id,entity_type,entity_id)
);
create table if not exists public.cmms_floor_plan (
  floor_plan_id uuid primary key default gen_random_uuid(), location_id uuid not null references public.cmms_location(location_id) on delete cascade,
  name text not null, image_bucket text not null default 'work-order-attachments', image_path text not null, width numeric, height numeric, archived_at timestamptz,
  created_by uuid references auth.users(id) on delete set null, created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create table if not exists public.cmms_floor_plan_pin (
  pin_id uuid primary key default gen_random_uuid(), floor_plan_id uuid not null references public.cmms_floor_plan(floor_plan_id) on delete cascade,
  equipment_id text references public.equipment_master(equipment_id) on delete set null, label text,
  x_ratio numeric not null check(x_ratio between 0 and 1), y_ratio numeric not null check(y_ratio between 0 and 1), color text,
  created_by uuid references auth.users(id) on delete set null, created_at timestamptz not null default now()
);
create or replace function public.rpc_cmms_checklist_templates(p_search text default null) returns jsonb language sql security definer set search_path=public as $$
 select coalesce(jsonb_agg(jsonb_build_object('templateId',t.template_id,'name',t.name,'description',coalesce(t.description,''),'active',t.active,'items',coalesce((select jsonb_agg(jsonb_build_object('itemId',i.template_item_id,'sequenceNo',i.sequence_no,'itemType',i.item_type,'label',i.label,'description',coalesce(i.description,''),'required',i.required,'unit',coalesce(i.unit,''),'minValue',i.min_value,'maxValue',i.max_value,'choices',i.choices) order by i.sequence_no) from public.cmms_checklist_template_item i where i.template_id=t.template_id),'[]'::jsonb)) order by t.updated_at desc),'[]'::jsonb) from public.cmms_checklist_template t where t.archived_at is null and (p_search is null or t.name ilike '%'||p_search||'%'); $$;
create or replace function public.rpc_cmms_save_checklist_template(p_input jsonb) returns jsonb language plpgsql security definer set search_path=public as $$
declare v_role text; v_id uuid; v_item jsonb; v_seq int:=0; begin
 if auth.uid() is null then raise exception 'AUTH_REQUIRED'; end if; v_role:=public.current_app_role()::text; if v_role not in ('SUPERVISOR','MANAGER','ADMIN') then raise exception 'CHECKLIST_WRITE_ROLE_DENIED'; end if;
 if nullif(trim(coalesce(p_input->>'name','')),'') is null then raise exception 'CHECKLIST_NAME_REQUIRED'; end if; v_id:=nullif(p_input->>'templateId','')::uuid;
 if v_id is null then insert into public.cmms_checklist_template(name,description,created_by) values(trim(p_input->>'name'),nullif(trim(coalesce(p_input->>'description','')),''),auth.uid()) returning template_id into v_id;
 else update public.cmms_checklist_template set name=trim(p_input->>'name'),description=nullif(trim(coalesce(p_input->>'description','')),''),updated_at=now() where template_id=v_id; delete from public.cmms_checklist_template_item where template_id=v_id; end if;
 for v_item in select * from jsonb_array_elements(coalesce(p_input->'items','[]'::jsonb)) loop v_seq:=v_seq+1; insert into public.cmms_checklist_template_item(template_id,sequence_no,item_type,label,description,required,unit,min_value,max_value,choices,source_data) values(v_id,v_seq,upper(coalesce(v_item->>'itemType','CHECK')),trim(coalesce(v_item->>'label','')),nullif(trim(coalesce(v_item->>'description','')),''),coalesce((v_item->>'required')::boolean,false),nullif(trim(coalesce(v_item->>'unit','')),''),nullif(v_item->>'minValue','')::numeric,nullif(v_item->>'maxValue','')::numeric,coalesce(v_item->'choices','[]'::jsonb),v_item); end loop;
 return jsonb_build_object('templateId',v_id); end $$;
create or replace function public.rpc_cmms_custom_fields(p_entity_type text) returns jsonb language sql security definer set search_path=public as $$ select coalesce(jsonb_agg(jsonb_build_object('fieldId',field_id,'entityType',entity_type,'label',label,'fieldType',field_type,'required',required,'choices',choices,'sortOrder',sort_order) order by sort_order,label),'[]'::jsonb) from public.cmms_custom_field_definition where active and entity_type=upper(trim(p_entity_type)); $$;
create or replace function public.rpc_cmms_save_custom_field(p_input jsonb) returns jsonb language plpgsql security definer set search_path=public as $$
declare v_role text; v_id uuid; begin if auth.uid() is null then raise exception 'AUTH_REQUIRED'; end if; v_role:=public.current_app_role()::text; if v_role not in ('MANAGER','ADMIN') then raise exception 'CUSTOM_FIELD_ROLE_DENIED'; end if; v_id:=nullif(p_input->>'fieldId','')::uuid;
 if v_id is null then insert into public.cmms_custom_field_definition(entity_type,label,field_type,required,choices,sort_order,created_by) values(upper(trim(p_input->>'entityType')),trim(p_input->>'label'),upper(coalesce(p_input->>'fieldType','TEXT')),coalesce((p_input->>'required')::boolean,false),coalesce(p_input->'choices','[]'::jsonb),coalesce((p_input->>'sortOrder')::int,0),auth.uid()) returning field_id into v_id;
 else update public.cmms_custom_field_definition set label=trim(p_input->>'label'),field_type=upper(coalesce(p_input->>'fieldType',field_type)),required=coalesce((p_input->>'required')::boolean,required),choices=coalesce(p_input->'choices',choices),sort_order=coalesce((p_input->>'sortOrder')::int,sort_order),updated_at=now() where field_id=v_id; end if; return jsonb_build_object('fieldId',v_id); end $$;
create or replace function public.rpc_cmms_file_library(p_search text default null,p_entity_type text default null,p_entity_id text default null) returns jsonb language sql security definer set search_path=public as $$ select coalesce(jsonb_agg(jsonb_build_object('fileId',f.file_id,'fileName',f.file_name,'bucket',f.storage_bucket,'path',f.storage_path,'mimeType',coalesce(f.mime_type,''),'size',f.file_size_bytes,'description',coalesce(f.description,''),'tags',f.tags,'createdAt',f.created_at,'links',coalesce((select jsonb_agg(jsonb_build_object('entityType',l.entity_type,'entityId',l.entity_id)) from public.cmms_file_link l where l.file_id=f.file_id),'[]'::jsonb)) order by f.created_at desc),'[]'::jsonb) from public.cmms_file_library f where f.archived_at is null and (p_search is null or f.file_name ilike '%'||p_search||'%') and (p_entity_type is null or exists(select 1 from public.cmms_file_link l where l.file_id=f.file_id and l.entity_type=upper(p_entity_type) and l.entity_id=p_entity_id)); $$;
create or replace function public.rpc_cmms_register_file(p_input jsonb) returns jsonb language plpgsql security definer set search_path=public as $$
declare v_id uuid; v_role text; begin if auth.uid() is null then raise exception 'AUTH_REQUIRED'; end if; v_role:=public.current_app_role()::text; if v_role not in ('MAINTENANCE','SUPERVISOR','MANAGER','ADMIN') then raise exception 'FILE_WRITE_ROLE_DENIED'; end if;
 insert into public.cmms_file_library(file_name,storage_bucket,storage_path,mime_type,file_size_bytes,description,tags,created_by) values(trim(p_input->>'fileName'),coalesce(nullif(p_input->>'bucket',''),'work-order-attachments'),trim(p_input->>'path'),nullif(p_input->>'mimeType',''),nullif(p_input->>'size','')::bigint,nullif(p_input->>'description',''),coalesce(array(select jsonb_array_elements_text(coalesce(p_input->'tags','[]'::jsonb))),'{}'::text[]),auth.uid()) on conflict(storage_bucket,storage_path) do update set file_name=excluded.file_name,description=excluded.description,updated_at=now() returning file_id into v_id;
 if nullif(p_input->>'entityType','') is not null and nullif(p_input->>'entityId','') is not null then insert into public.cmms_file_link(file_id,entity_type,entity_id,created_by) values(v_id,upper(p_input->>'entityType'),p_input->>'entityId',auth.uid()) on conflict do nothing; end if; return jsonb_build_object('fileId',v_id); end $$;
create or replace function public.rpc_cmms_floor_plans(p_location_id uuid) returns jsonb language sql security definer set search_path=public as $$ select coalesce(jsonb_agg(jsonb_build_object('floorPlanId',f.floor_plan_id,'locationId',f.location_id,'name',f.name,'bucket',f.image_bucket,'path',f.image_path,'pins',coalesce((select jsonb_agg(jsonb_build_object('pinId',p.pin_id,'equipmentId',p.equipment_id,'label',coalesce(p.label,''),'x',p.x_ratio,'y',p.y_ratio,'color',coalesce(p.color,''))) from public.cmms_floor_plan_pin p where p.floor_plan_id=f.floor_plan_id),'[]'::jsonb)) order by f.created_at desc),'[]'::jsonb) from public.cmms_floor_plan f where f.location_id=p_location_id and f.archived_at is null; $$;
create or replace function public.rpc_cmms_save_floor_plan(p_input jsonb) returns jsonb language plpgsql security definer set search_path=public as $$ declare v_role text; v_id uuid; begin if auth.uid() is null then raise exception 'AUTH_REQUIRED'; end if; v_role:=public.current_app_role()::text; if v_role not in ('SUPERVISOR','MANAGER','ADMIN') then raise exception 'FLOOR_PLAN_ROLE_DENIED'; end if; insert into public.cmms_floor_plan(location_id,name,image_bucket,image_path,created_by) values((p_input->>'locationId')::uuid,trim(p_input->>'name'),coalesce(nullif(p_input->>'bucket',''),'work-order-attachments'),trim(p_input->>'path'),auth.uid()) returning floor_plan_id into v_id; return jsonb_build_object('floorPlanId',v_id); end $$;
create or replace function public.rpc_cmms_add_floor_plan_pin(p_input jsonb) returns jsonb language plpgsql security definer set search_path=public as $$ declare v_role text; v_id uuid; begin if auth.uid() is null then raise exception 'AUTH_REQUIRED'; end if; v_role:=public.current_app_role()::text; if v_role not in ('SUPERVISOR','MANAGER','ADMIN') then raise exception 'FLOOR_PLAN_ROLE_DENIED'; end if; insert into public.cmms_floor_plan_pin(floor_plan_id,equipment_id,label,x_ratio,y_ratio,color,created_by) values((p_input->>'floorPlanId')::uuid,nullif(p_input->>'equipmentId',''),nullif(p_input->>'label',''),(p_input->>'x')::numeric,(p_input->>'y')::numeric,nullif(p_input->>'color',''),auth.uid()) returning pin_id into v_id; return jsonb_build_object('pinId',v_id); end $$;
create or replace function public.rpc_cmms_downtime_history(p_equipment_id text) returns jsonb language sql security definer set search_path=public as $$ select coalesce(jsonb_agg(jsonb_build_object('downtimeId',downtime_id,'equipmentId',equipment_id,'workOrderId',work_order_id,'startedAt',started_at,'endedAt',ended_at,'reason',coalesce(source_data->>'reason',''),'durationMinutes',case when started_at is null then 0 else round(extract(epoch from (coalesce(ended_at,now())-started_at))/60.0,1) end) order by started_at desc),'[]'::jsonb) from public.downtime_event where equipment_id=trim(p_equipment_id); $$;
create or replace function public.rpc_cmms_set_downtime(p_input jsonb) returns jsonb language plpgsql security definer set search_path=public as $$ declare v_role text; v_id text; v_action text; begin if auth.uid() is null then raise exception 'AUTH_REQUIRED'; end if; v_role:=public.current_app_role()::text; if v_role not in ('MAINTENANCE','SUPERVISOR','MANAGER','ADMIN') then raise exception 'DOWNTIME_ROLE_DENIED'; end if; v_action:=upper(coalesce(p_input->>'action','START'));
 if v_action='START' then if exists(select 1 from public.downtime_event where equipment_id=trim(p_input->>'equipmentId') and ended_at is null) then raise exception 'DOWNTIME_ALREADY_OPEN'; end if; v_id:='DT-'||to_char(clock_timestamp(),'YYYYMMDDHH24MISSMS')||'-'||substr(replace(gen_random_uuid()::text,'-',''),1,6); insert into public.downtime_event(downtime_id,equipment_id,work_order_id,started_at,source_data) values(v_id,trim(p_input->>'equipmentId'),nullif(p_input->>'workOrderId',''),coalesce(nullif(p_input->>'startedAt','')::timestamptz,now()),jsonb_build_object('reason',coalesce(p_input->>'reason',''),'createdBy',auth.uid()));
 else select downtime_id into v_id from public.downtime_event where equipment_id=trim(p_input->>'equipmentId') and ended_at is null order by started_at desc limit 1 for update; if v_id is null then raise exception 'OPEN_DOWNTIME_NOT_FOUND'; end if; update public.downtime_event set ended_at=coalesce(nullif(p_input->>'endedAt','')::timestamptz,now()),source_data=source_data||jsonb_build_object('endReason',coalesce(p_input->>'reason',''),'endedBy',auth.uid()) where downtime_id=v_id; end if; return jsonb_build_object('downtimeId',v_id,'action',v_action); end $$;
revoke all on function public.rpc_cmms_save_checklist_template(jsonb), public.rpc_cmms_save_custom_field(jsonb), public.rpc_cmms_register_file(jsonb), public.rpc_cmms_save_floor_plan(jsonb), public.rpc_cmms_add_floor_plan_pin(jsonb), public.rpc_cmms_set_downtime(jsonb) from public,anon;
grant execute on function public.rpc_cmms_checklist_templates(text), public.rpc_cmms_save_checklist_template(jsonb), public.rpc_cmms_custom_fields(text), public.rpc_cmms_save_custom_field(jsonb), public.rpc_cmms_file_library(text,text,text), public.rpc_cmms_register_file(jsonb), public.rpc_cmms_floor_plans(uuid), public.rpc_cmms_save_floor_plan(jsonb), public.rpc_cmms_add_floor_plan_pin(jsonb), public.rpc_cmms_downtime_history(text), public.rpc_cmms_set_downtime(jsonb) to authenticated;
